-- TRIDENT OPS standalone shell.
-- Existing SNOWCORE_REAL and PNEUMORA objects are read, never replaced.

USE ROLE ACCOUNTADMIN;

SET current_user_name = CURRENT_USER();

CREATE ROLE IF NOT EXISTS TRIDENT_OPS_ROLE
  COMMENT = 'Runs the TRIDENT OPS hackathon command center';
GRANT ROLE TRIDENT_OPS_ROLE TO ROLE SYSADMIN;
GRANT ROLE TRIDENT_OPS_ROLE TO USER IDENTIFIER($current_user_name);

CREATE WAREHOUSE IF NOT EXISTS TRIDENT_OPS_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'TRIDENT OPS warehouse-runtime Streamlit';
GRANT OWNERSHIP ON WAREHOUSE TRIDENT_OPS_WH TO ROLE TRIDENT_OPS_ROLE COPY CURRENT GRANTS;

CREATE DATABASE IF NOT EXISTS TRIDENT_OPS
  COMMENT = 'Standalone action and app layer; source plants remain isolated';
GRANT OWNERSHIP ON DATABASE TRIDENT_OPS TO ROLE TRIDENT_OPS_ROLE COPY CURRENT GRANTS;

-- Read grants are deliberately explicit. No source object is writable.
GRANT USAGE ON DATABASE SNOWCORE_REAL TO ROLE TRIDENT_OPS_ROLE;
GRANT USAGE ON SCHEMA SNOWCORE_REAL.GOLD TO ROLE TRIDENT_OPS_ROLE;
GRANT USAGE ON SCHEMA SNOWCORE_REAL.ML TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.GOLD.V_EXECUTIVE_KPI TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.GOLD.V_EXECUTIVE_FLEET TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.GOLD.V_EXECUTIVE_ACTION_QUEUE TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.GOLD.V_ROOT_CAUSE_ALARM TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.GOLD.V_ANALYST_DECISION_CONTEXT TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.GOLD.V_RISK_WORK_ORDER_SUMMARY TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON VIEW SNOWCORE_REAL.ML.V_PIADE_RESEARCH_CHAMPION TO ROLE TRIDENT_OPS_ROLE;

GRANT USAGE ON DATABASE PNEUMORA TO ROLE TRIDENT_OPS_ROLE;
GRANT USAGE ON SCHEMA PNEUMORA.CORE TO ROLE TRIDENT_OPS_ROLE;
GRANT USAGE ON SCHEMA PNEUMORA.ML TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON TABLE PNEUMORA.CORE.FAILURES TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON TABLE PNEUMORA.ML.ALERTS TO ROLE TRIDENT_OPS_ROLE;
GRANT SELECT ON TABLE PNEUMORA.ML.EVIDENCE TO ROLE TRIDENT_OPS_ROLE;

USE ROLE TRIDENT_OPS_ROLE;
USE DATABASE TRIDENT_OPS;

CREATE SCHEMA IF NOT EXISTS OPS COMMENT = 'Operator-entered triage actions only';
CREATE SCHEMA IF NOT EXISTS APP COMMENT = 'TRIDENT OPS Streamlit source';

CREATE STAGE IF NOT EXISTS APP.STREAMLIT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Source files for the TRIDENT OPS warehouse-runtime app';
