-- A reload-safe, idempotent black-box recorder for operator decisions.

USE ROLE TRIDENT_OPS_ROLE;
USE WAREHOUSE TRIDENT_OPS_WH;
USE DATABASE TRIDENT_OPS;
USE SCHEMA OPS;

CREATE TABLE IF NOT EXISTS TRIAGE_ACTION (
  ACTION_ID        STRING        NOT NULL,
  IDEMPOTENCY_KEY  STRING        NOT NULL,
  CREATED_AT       TIMESTAMP_TZ  NOT NULL,
  LAST_SEEN_AT     TIMESTAMP_TZ  NOT NULL,
  PLANT_CODE       STRING        NOT NULL,
  MACHINE_CODE     STRING        NOT NULL,
  SOURCE_KEY       STRING        NOT NULL,
  ACTION           STRING        NOT NULL,
  STATUS           STRING        NOT NULL,
  NOTE             STRING,
  ACTOR            STRING        NOT NULL,
  DATA_ORIGIN      STRING        NOT NULL,
  SOURCE_SYSTEM    STRING        NOT NULL,
  CONSTRAINT PK_TRIAGE_ACTION PRIMARY KEY (ACTION_ID)
)
COMMENT = 'Operator-entered decisions. Primary key is informational; idempotency is enforced by MERGE.';

CREATE OR REPLACE PROCEDURE RECORD_TRIAGE_ACTION(
  P_PLANT_CODE STRING,
  P_MACHINE_CODE STRING,
  P_SOURCE_KEY STRING,
  P_ACTION STRING,
  P_NOTE STRING,
  P_ACTOR STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_KEY STRING;
  V_ID STRING;
  V_NOW TIMESTAMP_TZ;
BEGIN
  IF (P_PLANT_CODE IS NULL OR P_PLANT_CODE <> 'PLANT_B') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Only PIADE PLANT_B actions are accepted');
  END IF;
  IF (P_MACHINE_CODE IS NULL OR P_MACHINE_CODE NOT IN ('s_1','s_2','s_3','s_4','s_5')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Unknown PIADE machine');
  END IF;
  IF (P_ACTION IS NULL OR P_ACTION NOT IN ('ACKNOWLEDGE','INSPECTION','SNOOZE')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Unsupported action');
  END IF;
  IF (P_SOURCE_KEY IS NULL OR LENGTH(TRIM(P_SOURCE_KEY)) = 0) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'SOURCE_KEY is required');
  END IF;

  V_KEY := SHA2(
    P_PLANT_CODE || '|' || P_MACHINE_CODE || '|' || P_SOURCE_KEY || '|' || P_ACTION,
    256
  );
  V_ID := 'TRI-' || SUBSTR(V_KEY, 1, 20);
  V_NOW := CURRENT_TIMESTAMP();

  MERGE INTO TRIDENT_OPS.OPS.TRIAGE_ACTION target
  USING (
    SELECT
      :V_ID AS ACTION_ID,
      :V_KEY AS IDEMPOTENCY_KEY,
      :V_NOW AS EVENT_AT,
      :P_PLANT_CODE AS PLANT_CODE,
      :P_MACHINE_CODE AS MACHINE_CODE,
      :P_SOURCE_KEY AS SOURCE_KEY,
      :P_ACTION AS ACTION,
      LEFT(COALESCE(:P_NOTE, ''), 500) AS NOTE,
      COALESCE(NULLIF(TRIM(:P_ACTOR), ''), 'UNKNOWN') AS ACTOR
  ) source
  ON target.IDEMPOTENCY_KEY = source.IDEMPOTENCY_KEY
  WHEN MATCHED THEN UPDATE SET
    LAST_SEEN_AT = source.EVENT_AT,
    NOTE = IFF(source.NOTE = '', target.NOTE, source.NOTE),
    ACTOR = source.ACTOR
  WHEN NOT MATCHED THEN INSERT (
    ACTION_ID, IDEMPOTENCY_KEY, CREATED_AT, LAST_SEEN_AT,
    PLANT_CODE, MACHINE_CODE, SOURCE_KEY, ACTION, STATUS, NOTE,
    ACTOR, DATA_ORIGIN, SOURCE_SYSTEM
  ) VALUES (
    source.ACTION_ID, source.IDEMPOTENCY_KEY, source.EVENT_AT, source.EVENT_AT,
    source.PLANT_CODE, source.MACHINE_CODE, source.SOURCE_KEY, source.ACTION,
    IFF(source.ACTION = 'SNOOZE', 'SNOOZED', 'OPEN'), source.NOTE,
    source.ACTOR, 'OPERATOR_ENTRY', 'TRIDENT_OPS_STREAMLIT'
  );

  RETURN (
    SELECT OBJECT_CONSTRUCT(
      'ok', TRUE,
      'action_id', ACTION_ID,
      'created_at', CREATED_AT,
      'last_seen_at', LAST_SEEN_AT,
      'deduplicated', CREATED_AT <> LAST_SEEN_AT,
      'action', ACTION,
      'status', STATUS
    )
    FROM TRIDENT_OPS.OPS.TRIAGE_ACTION
    WHERE IDEMPOTENCY_KEY = :V_KEY
  );
END;
$$;

GRANT USAGE ON PROCEDURE RECORD_TRIAGE_ACTION(STRING,STRING,STRING,STRING,STRING,STRING)
  TO ROLE TRIDENT_OPS_ROLE;
