"""Generate Bronze DDL and COPY statements from the real CSV headers.

Hand-typing 123 alarm columns and 164 hourly columns invites silent mistakes,
so the DDL is derived from the files themselves. Rerunning this after a source
refresh regenerates the script rather than patching it.

Writes sql/11_bronze_load.sql.
"""

from pathlib import Path

RAW = Path("data/raw")
OUT = Path("sql/11_bronze_load.sql")

# Source column -> Bronze column, where the raw name cannot be used as-is.
# "end" is reserved in Snowflake; "" is the unnamed pandas index; the unit
# suffixes record what the profiling run measured.
RENAMES = {
    "": "ROW_IDX",
    "_time": "TIME_UTC",
    "_serial": "SERIAL",
    "interval_start": "INTERVAL_START",
    "equipment_ID": "EQUIPMENT_ID",
    "alarm": "ALARM_CODE",
    "type": "STATE_TYPE",
    "start": "START_EPOCH",
    "end": "END_EPOCH",
    "elapsed": "ELAPSED_MS",
    "pi": "PI_COUNTER",
    "po": "PO_COUNTER",
    "speed": "SPEED_PPH",
    "count_sum": "COUNT_SUM",
    "#changes": "STATE_CHANGES",
    "%idle": "PCT_IDLE",
    "%production": "PCT_PRODUCTION",
    "%downtime": "PCT_DOWNTIME",
    "%performance_loss": "PCT_PERFORMANCE_LOSS",
    "%scheduled_downtime": "PCT_SCHEDULED_DOWNTIME",
}


def bronze_name(raw: str) -> str:
    if raw in RENAMES:
        return RENAMES[raw]
    # State-transition columns arrive as "production/downtime".
    if "/" in raw:
        return "TRANS_" + raw.replace("/", "_TO_").upper()
    return raw.upper()


def sql_type(raw: str) -> str:
    if raw in ("_time", "interval_start"):
        return "TIMESTAMP_TZ"
    if raw in ("_serial", "equipment_ID", "alarm", "type"):
        return "VARCHAR"
    if raw in ("start", "end"):
        return "NUMBER(20,7)"
    if raw == "":
        return "NUMBER(38,0)"
    return "FLOAT"


def header_of(path: Path) -> list[str]:
    with path.open("r", encoding="utf-8") as fh:
        return next(fh).rstrip("\n").rstrip("\r").split(",")


def build(
    table: str,
    stage_file: str,
    source_key: str,
    csv_path: Path,
    comment: str,
    expected_rows: int,
    ts_is_tz: bool = True,
) -> str:
    cols = header_of(csv_path)
    names = [bronze_name(c) for c in cols]
    types = [sql_type(c) for c in cols]
    if not ts_is_tz:
        types = ["TIMESTAMP_NTZ" if t == "TIMESTAMP_TZ" else t for t in types]

    ddl_cols = ",\n".join(f"  {n:<24} {t}" for n, t in zip(names, types))
    select_cols = ",\n".join(
        f"    ${i + 1}::{t:<14} AS {n}" for i, (n, t) in enumerate(zip(names, types))
    )
    mapping = "\n".join(
        f"     {raw or '(unnamed index)':<24} -> {n}"
        for raw, n in zip(cols, names)
        if raw != n
    )

    return f"""
/* ---------------------------------------------------------------------------
   {table}
   {comment}
   Source column renames (everything else keeps its published name, upper-cased):
{mapping}
   --------------------------------------------------------------------------- */

CREATE OR REPLACE TABLE BRONZE.{table} (
{ddl_cols},
  SOURCE_KEY               VARCHAR       NOT NULL,
  SOURCE_FILE              VARCHAR       NOT NULL,
  DATA_ORIGIN              VARCHAR       NOT NULL,
  LOAD_TS                  TIMESTAMP_NTZ NOT NULL
)
COMMENT = '{comment}';

COPY INTO BRONZE.{table}
FROM (
  SELECT
{select_cols},
    '{source_key}'               AS SOURCE_KEY,
    METADATA$FILENAME            AS SOURCE_FILE,
    'OBSERVED'                   AS DATA_ORIGIN,
    CURRENT_TIMESTAMP()          AS LOAD_TS
  FROM @BRONZE.SRC_STAGE/{stage_file}
)
FILE_FORMAT = (FORMAT_NAME = BRONZE.FF_CSV_LOAD)
ON_ERROR = ABORT_STATEMENT;

-- Expected {expected_rows} rows from the published file.
SELECT '{table}' AS TARGET,
       COUNT(*) AS LOADED_ROWS,
       {expected_rows} AS EXPECTED_ROWS,
       COUNT(*) = {expected_rows} AS ROWS_MATCH
FROM BRONZE.{table};
"""


def main() -> None:
    header = """/* ============================================================================
   Bronze load for the two real plants.

   GENERATED by scripts/generate_bronze_sql.py from the actual CSV headers.
   Do not hand-edit; change the generator and rerun.

   Plant A  CoMoPI  DOI 10.5281/zenodo.7572501  CC BY 4.0
   Plant B  PIADE   DOI 10.5281/zenodo.7071747  CC BY 4.0

   Bronze preserves published values as-is. The only changes are column names
   that SQL cannot accept bare, listed per table below.
   ========================================================================= */

USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWCORE_REAL;
USE WAREHOUSE COMPUTE_WH;
ALTER SESSION SET QUERY_TAG = 'snowcore-real|coco|bronze-load';
"""

    blocks = [
        header,
        build(
            "COMOPI_SENSORS_RAW",
            "comopi_sensors.csv.gz",
            "COMOPI_SENSORS",
            RAW / "comopi/industrial_dataset_sensors_10m_agg.csv",
            "Plant A: 16 anonymised sensors on the watertight-closure module, 10-minute averages, rescaled to [0,1].",
            15704,
        ),
        build(
            "COMOPI_ALARMS_RAW",
            "comopi_alarms.csv.gz",
            "COMOPI_ALARMS",
            RAW / "comopi/industrial_dataset_alarm_10m_agg.csv",
            "Plant A: counts of alarms AL_1..AL_123 per 10-minute window.",
            150650,
        ),
        build(
            "PIADE_INTERVALS_RAW",
            "piade_intervals.csv.gz",
            "PIADE_INTERVALS",
            RAW / "piade/raw_data.csv",
            "Plant B: production intervals with machine state, stop alarm, cumulative package counters and speed.",
            429394,
        ),
        build(
            "PIADE_HOURLY_RAW",
            "piade_hourly.csv.gz",
            "PIADE_HOURLY",
            RAW / "piade/sequences_1h_data.csv",
            "Plant B: publisher hourly aggregate, used to cross-check our own derivation.",
            23376,
            ts_is_tz=False,
        ),
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(blocks), encoding="utf-8")
    print(f"wrote {OUT} ({len(OUT.read_text(encoding='utf-8').splitlines())} lines)")


if __name__ == "__main__":
    main()
