-- PNEUMORA standalone Snowflake foundation.
-- This script intentionally creates no SNOWCORE_* or AXISGUARD_* references.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS PNEUMORA_ROLE
  COMMENT = 'Owner and runtime role for the isolated PNEUMORA product';
GRANT ROLE PNEUMORA_ROLE TO ROLE SYSADMIN;
SET PNEUMORA_DEPLOYER = CURRENT_USER();
GRANT ROLE PNEUMORA_ROLE TO USER IDENTIFIER($PNEUMORA_DEPLOYER);

CREATE WAREHOUSE IF NOT EXISTS PNEUMORA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'PNEUMORA load and Streamlit warehouse';

CREATE DATABASE IF NOT EXISTS PNEUMORA
  COMMENT = 'Early air-leak co-pilot for the MetroPT-3 air production unit';
CREATE SCHEMA IF NOT EXISTS PNEUMORA.CORE COMMENT = 'Observed MetroPT-3 telemetry, reported failures and daily measurements';
CREATE SCHEMA IF NOT EXISTS PNEUMORA.ML   COMMENT = 'Co-pilot alerts, failure zoom windows and frozen evidence documents';
CREATE SCHEMA IF NOT EXISTS PNEUMORA.OPS  COMMENT = 'Clearly labelled demonstration maintenance records and example factory scenario';
CREATE SCHEMA IF NOT EXISTS PNEUMORA.APP  COMMENT = 'Streamlit source and app object';

GRANT OWNERSHIP ON DATABASE PNEUMORA TO ROLE PNEUMORA_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE PNEUMORA TO ROLE PNEUMORA_ROLE COPY CURRENT GRANTS;
GRANT USAGE, OPERATE ON WAREHOUSE PNEUMORA_WH TO ROLE PNEUMORA_ROLE;
