-- PNEUMORA tables. Column order matches data/snowflake/manifest.json.

USE ROLE PNEUMORA_ROLE;
USE WAREHOUSE PNEUMORA_WH;

CREATE FILE FORMAT IF NOT EXISTS PNEUMORA.CORE.CSV_GZ
  TYPE = CSV COMPRESSION = GZIP SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('') EMPTY_FIELD_AS_NULL = TRUE;
CREATE STAGE IF NOT EXISTS PNEUMORA.CORE.LOAD_STAGE COMMENT = 'Export files from scripts/export_snowflake.py';
CREATE STAGE IF NOT EXISTS PNEUMORA.APP.STREAMLIT_STAGE DIRECTORY = (ENABLE = TRUE) COMMENT = 'PNEUMORA Streamlit source';

CREATE OR REPLACE TABLE PNEUMORA.CORE.TELEMETRY_5M (
  TS TIMESTAMP_NTZ, RESERVOIRS FLOAT, TP3 FLOAT, MOTOR_CURRENT FLOAT, OIL_TEMPERATURE FLOAT,
  MPG FLOAT, LPS FLOAT, LOADED_RUN_MINUTES FLOAT, COPILOT_FLAG BOOLEAN, DATA_ORIGIN VARCHAR
) COMMENT = 'Observed MetroPT-3 telemetry, 5-minute means, with the frozen leak-detector flag';

CREATE OR REPLACE TABLE PNEUMORA.CORE.FAILURES (
  FAILURE_ID VARCHAR, START_TS TIMESTAMP_NTZ, END_TS TIMESTAMP_NTZ, REPORT VARCHAR,
  REMOVAL_DEADLINE TIMESTAMP_NTZ, ONSET_PRECISION VARCHAR, COPILOT_FIRST TIMESTAMP_NTZ,
  COPILOT_MINUTES_AFTER_START FLOAT, COPILOT_MINUTES_BEFORE_END FLOAT,
  LPS_FIRST TIMESTAMP_NTZ, LPS_MINUTES_AFTER_START FLOAT
) COMMENT = 'Reported MetroPT-3 air-leak failures and first in-time alerts';

CREATE OR REPLACE TABLE PNEUMORA.ML.FAILURE_ZOOM (
  FAILURE_ID VARCHAR, TS TIMESTAMP_NTZ, LOADED FLOAT, RESERVOIRS FLOAT, LPS FLOAT
) COMMENT = 'Observed signals around each reported failure';

CREATE OR REPLACE TABLE PNEUMORA.ML.PREDICTION_CASES (
  CASE_ID VARCHAR, UNIT VARCHAR, COMPRESSOR VARCHAR, EVENT_ID VARCHAR, KIND VARCHAR, START_TS TIMESTAMP_NTZ,
  END_TS TIMESTAMP_NTZ, LAST_USEFUL_ALERT TIMESTAMP_NTZ, PREDICTED_IN_TIME BOOLEAN, FIRST_ALERT TIMESTAMP_NTZ,
  MINUTES_BEFORE_END FLOAT, MINUTES_AFTER_START FLOAT, ALARM_IN_TIME BOOLEAN, ALARM_FIRST TIMESTAMP_NTZ,
  ALARM_MINUTES_BEFORE_END FLOAT, CONFIG VARCHAR
) COMMENT = 'Each of the nine failures on three compressors, scored by the held-out leak predictor and the existing alarm';

CREATE OR REPLACE TABLE PNEUMORA.ML.PREDICTION_ZOOM (
  CASE_ID VARCHAR, TS TIMESTAMP_NTZ, LOADED_RUN_MINUTES FLOAT, PRESSURE FLOAT, ALERTING BOOLEAN, ALARM_ON BOOLEAN
) COMMENT = 'Observed signals and alert flags from 12 h before to 3 h after each failure';

CREATE OR REPLACE TABLE PNEUMORA.ML.ALERTS (
  SOURCE VARCHAR, ALERT_ID VARCHAR, RAISED_AT TIMESTAMP_NTZ, CLEARED_AT TIMESTAMP_NTZ, OUTCOME VARCHAR,
  FAILURE_ID VARCHAR, MINUTES_AFTER_START FLOAT, MINUTES_BEFORE_END FLOAT, PEAK_LOADED_MINUTES FLOAT
) COMMENT = 'Leak-detector alerts and existing low-pressure alarm episodes, scored against reported failures';

CREATE OR REPLACE TABLE PNEUMORA.ML.EVIDENCE (DOC_KEY VARCHAR, DOC_JSON VARCHAR)
  COMMENT = 'Frozen study results and track-record summary as JSON documents';

CREATE OR REPLACE TABLE PNEUMORA.OPS.WORK_ORDERS (
  ORDER_ID VARCHAR, WARNING_ID VARCHAR, CREATED_AT TIMESTAMP_NTZ, PRIORITY VARCHAR, PROBLEM VARCHAR,
  ACTION VARCHAR, TECHNICIAN VARCHAR, PART VARCHAR, STATUS VARCHAR, ASSET VARCHAR, NOTE VARCHAR, DATA_ORIGIN VARCHAR
) COMMENT = 'Demonstration maintenance records, not real railway work orders';

CREATE OR REPLACE TABLE PNEUMORA.OPS.PARTS (
  SKU VARCHAR, NAME VARCHAR, STOCK NUMBER, REORDER_AT NUMBER, COST_EUR FLOAT, DATA_ORIGIN VARCHAR
) COMMENT = 'Demonstration parts stock';

CREATE OR REPLACE TABLE PNEUMORA.OPS.TECHNICIANS (
  TECHNICIAN_ID VARCHAR, NAME VARCHAR, ROLE VARCHAR, SHIFT VARCHAR, DATA_ORIGIN VARCHAR
) COMMENT = 'Demonstration crew';

CREATE OR REPLACE TABLE PNEUMORA.CORE.DAILY_KPIS (
  DATE DATE, SAMPLES NUMBER, TELEMETRY_COVERAGE FLOAT, COMPRESSOR_RUNTIME FLOAT, LOADED_TIME FLOAT,
  TIME_UNDER_STRAIN FLOAT, DATA_ORIGIN VARCHAR
) COMMENT = 'Daily measurements derived from observed telemetry';

CREATE OR REPLACE TABLE PNEUMORA.OPS.FACTORY_SCENARIO (
  DATE DATE, PLANNED_MINUTES NUMBER, DOWNTIME_MINUTES FLOAT, IDEAL_UNITS NUMBER, TOTAL_UNITS NUMBER,
  GOOD_UNITS NUMBER, AVAILABILITY FLOAT, PERFORMANCE FLOAT, QUALITY FLOAT, OEE FLOAT,
  ESTIMATED_DOWNTIME_COST_EUR FLOAT, DATA_ORIGIN VARCHAR, DISCLAIMER VARCHAR
) COMMENT = 'Example factory assumptions, not this train''s real production or cost';
