-- Load the export. Replace <REPO_ROOT> with the absolute repository path using forward slashes.
-- PUT needs a client session (Cortex Code CLI, Snowflake CLI or SnowSQL), not a Snowsight worksheet.

USE ROLE PNEUMORA_ROLE;
USE WAREHOUSE PNEUMORA_WH;

PUT 'file://<REPO_ROOT>/pneumora/data/snowflake/*.csv.gz' @PNEUMORA.CORE.LOAD_STAGE AUTO_COMPRESS = FALSE OVERWRITE = TRUE;

COPY INTO PNEUMORA.CORE.TELEMETRY_5M   FROM @PNEUMORA.CORE.LOAD_STAGE/telemetry_5m.csv.gz     FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.CORE.FAILURES       FROM @PNEUMORA.CORE.LOAD_STAGE/failures.csv.gz         FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.ML.FAILURE_ZOOM     FROM @PNEUMORA.CORE.LOAD_STAGE/failure_zoom.csv.gz     FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.ML.ALERTS           FROM @PNEUMORA.CORE.LOAD_STAGE/alerts.csv.gz           FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.ML.EVIDENCE         FROM @PNEUMORA.CORE.LOAD_STAGE/evidence.csv.gz         FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.OPS.WORK_ORDERS     FROM @PNEUMORA.CORE.LOAD_STAGE/work_orders.csv.gz      FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.OPS.PARTS           FROM @PNEUMORA.CORE.LOAD_STAGE/parts.csv.gz            FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.OPS.TECHNICIANS     FROM @PNEUMORA.CORE.LOAD_STAGE/technicians.csv.gz      FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.CORE.DAILY_KPIS     FROM @PNEUMORA.CORE.LOAD_STAGE/daily_kpis.csv.gz       FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
COPY INTO PNEUMORA.OPS.FACTORY_SCENARIO FROM @PNEUMORA.CORE.LOAD_STAGE/factory_scenario.csv.gz FILE_FORMAT = PNEUMORA.CORE.CSV_GZ ON_ERROR = ABORT_STATEMENT;
