-- Snowflake-native anomaly detection on the leak signal, scored against the reported failures.
--
-- Declared before scoring: train on February-March 2020 (no failure labels), detect on
-- April onward with a 99% prediction interval, and raise an alert only when six
-- consecutive 5-minute bins (30 minutes) are anomalous. Alerts within 30 minutes merge.
-- Scoring matches autoresearch/precursor_study.py: warned before onset means an alert in
-- [start - 6 h, start); caught in time means an alert in [start - 2 h, end - 2 h]; an alert
-- outside every [start - 24 h, end] is false.

USE ROLE PNEUMORA_ROLE;
USE WAREHOUSE PNEUMORA_WH;

-- Tables, not views: DETECT_ANOMALIES cannot expand a view over another schema.
DROP VIEW IF EXISTS PNEUMORA.ML.V_LEAK_SIGNAL_TRAIN;
DROP VIEW IF EXISTS PNEUMORA.ML.V_LEAK_SIGNAL_SCORE;

CREATE OR REPLACE TABLE PNEUMORA.ML.LEAK_SIGNAL_TRAIN AS
SELECT TS, LOADED_RUN_MINUTES::FLOAT AS LOADED_RUN_MINUTES
FROM PNEUMORA.CORE.TELEMETRY_5M
WHERE TS < '2020-04-01' AND LOADED_RUN_MINUTES IS NOT NULL;

CREATE OR REPLACE TABLE PNEUMORA.ML.LEAK_SIGNAL_SCORE AS
SELECT TS, LOADED_RUN_MINUTES::FLOAT AS LOADED_RUN_MINUTES
FROM PNEUMORA.CORE.TELEMETRY_5M
WHERE TS >= '2020-04-01' AND LOADED_RUN_MINUTES IS NOT NULL;

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION PNEUMORA.ML.LEAK_ANOMALY_MODEL(
  INPUT_DATA => TABLE(PNEUMORA.ML.LEAK_SIGNAL_TRAIN),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'LOADED_RUN_MINUTES',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE PNEUMORA.ML.NATIVE_ANOMALIES
  COMMENT = 'SNOWFLAKE.ML.ANOMALY_DETECTION output on observed MetroPT-3 loaded-run minutes' AS
SELECT * FROM TABLE(PNEUMORA.ML.LEAK_ANOMALY_MODEL!DETECT_ANOMALIES(
  INPUT_DATA => TABLE(PNEUMORA.ML.LEAK_SIGNAL_SCORE),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'LOADED_RUN_MINUTES',
  CONFIG_OBJECT => {'prediction_interval': 0.99}
));

CREATE OR REPLACE TABLE PNEUMORA.ML.NATIVE_ANOMALY_EPISODES
  COMMENT = 'Merged alerts: six consecutive anomalous 5-minute bins, merged within 30 minutes' AS
WITH scored AS (
  SELECT TS,
         SUM(IFF(IS_ANOMALY, 1, 0)) OVER (ORDER BY TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS ANOMALOUS_6,
         LAG(TS, 5) OVER (ORDER BY TS) AS TS_5_BACK
  FROM PNEUMORA.ML.NATIVE_ANOMALIES
), flagged AS (
  SELECT TS FROM scored WHERE ANOMALOUS_6 = 6 AND DATEDIFF('minute', TS_5_BACK, TS) = 25
), starts AS (
  SELECT TS, IFF(LAG(TS) OVER (ORDER BY TS) IS NULL OR DATEDIFF('minute', LAG(TS) OVER (ORDER BY TS), TS) > 30, 1, 0) AS NEW_EPISODE
  FROM flagged
), numbered AS (
  SELECT TS, SUM(NEW_EPISODE) OVER (ORDER BY TS ROWS UNBOUNDED PRECEDING) AS EPISODE FROM starts
)
SELECT EPISODE AS EPISODE_ID, MIN(TS) AS RAISED_AT, MAX(TS) AS LAST_FLAG FROM numbered GROUP BY EPISODE;

CREATE OR REPLACE TABLE PNEUMORA.ML.NATIVE_ANOMALY_EVAL
  COMMENT = 'Native anomaly detection scored against reported failures' AS
SELECT f.FAILURE_ID, f.START_TS, f.END_TS, f.ONSET_PRECISION,
       MIN(IFF(e.RAISED_AT >= DATEADD('hour', -6, f.START_TS) AND e.RAISED_AT < f.START_TS, e.RAISED_AT, NULL)) AS FIRST_BEFORE_ONSET,
       MIN(IFF(e.RAISED_AT BETWEEN DATEADD('minute', -120, f.START_TS) AND DATEADD('minute', -120, f.END_TS), e.RAISED_AT, NULL)) AS FIRST_IN_TIME
FROM PNEUMORA.CORE.FAILURES f
LEFT JOIN PNEUMORA.ML.NATIVE_ANOMALY_EPISODES e ON TRUE
GROUP BY f.FAILURE_ID, f.START_TS, f.END_TS, f.ONSET_PRECISION;

CREATE OR REPLACE TABLE PNEUMORA.ML.NATIVE_ANOMALY_SUMMARY
  COMMENT = 'Native anomaly detection tally: alerts, false alerts and healthy days' AS
WITH span AS (SELECT MIN(TS) AS S, MAX(TS) AS E FROM PNEUMORA.ML.NATIVE_ANOMALIES),
excluded AS (
  SELECT COALESCE(SUM(DATEDIFF('second', GREATEST(DATEADD('hour', -24, f.START_TS), span.S), LEAST(f.END_TS, span.E))), 0) / 86400 AS DAYS
  FROM PNEUMORA.CORE.FAILURES f, span WHERE f.END_TS > span.S
),
false_alerts AS (
  SELECT COUNT(*) AS N FROM PNEUMORA.ML.NATIVE_ANOMALY_EPISODES e
  WHERE NOT EXISTS (SELECT 1 FROM PNEUMORA.CORE.FAILURES f WHERE e.RAISED_AT BETWEEN DATEADD('hour', -24, f.START_TS) AND f.END_TS)
)
SELECT (SELECT COUNT(*) FROM PNEUMORA.ML.NATIVE_ANOMALY_EPISODES) AS ALERTS,
       false_alerts.N AS FALSE_ALERTS,
       DATEDIFF('second', span.S, span.E) / 86400 - excluded.DAYS AS HEALTHY_DAYS,
       false_alerts.N / NULLIF(DATEDIFF('second', span.S, span.E) / 86400 - excluded.DAYS, 0) AS FALSE_PER_HEALTHY_DAY,
       (SELECT COUNT(FIRST_BEFORE_ONSET) FROM PNEUMORA.ML.NATIVE_ANOMALY_EVAL) AS WARNED_BEFORE_ONSET,
       (SELECT COUNT(FIRST_IN_TIME) FROM PNEUMORA.ML.NATIVE_ANOMALY_EVAL) AS CAUGHT_IN_TIME,
       (SELECT COUNT(*) FROM PNEUMORA.ML.NATIVE_ANOMALY_EVAL) AS FAILURES,
       'SNOWFLAKE.ML.ANOMALY_DETECTION · train Feb-Mar 2020 · 99% interval · 30 min sustained' AS METHOD
FROM span, excluded, false_alerts;
