-- Work orders created and updated from the PNEUMORA app.
-- CREATE_WORK_ORDER is idempotent: the same source and problem return the existing order.
-- Rows written here carry DATA_ORIGIN = 'OPERATOR_ENTRY'. Re-running 01_tables.sql recreates
-- OPS.WORK_ORDERS and deletes them.

USE ROLE PNEUMORA_ROLE;
USE WAREHOUSE PNEUMORA_WH;

CREATE OR REPLACE PROCEDURE PNEUMORA.OPS.CREATE_WORK_ORDER(
  P_SOURCE_KEY VARCHAR, P_AT VARCHAR, P_PRIORITY VARCHAR, P_PROBLEM VARCHAR, P_ACTION VARCHAR,
  P_TECHNICIAN VARCHAR, P_PART VARCHAR, P_NOTE VARCHAR, P_ACTOR VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_KEY VARCHAR;
  V_ID VARCHAR;
  V_EXISTING NUMBER;
BEGIN
  IF (P_PRIORITY IS NULL OR P_PRIORITY NOT IN ('urgent', 'planned')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Priority must be urgent or planned');
  END IF;
  IF (P_PROBLEM IS NULL OR LENGTH(TRIM(P_PROBLEM)) = 0) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Describe the problem');
  END IF;
  V_KEY := SHA2('APU-01|' || COALESCE(NULLIF(TRIM(P_SOURCE_KEY), ''), P_AT) || '|' || TRIM(P_PROBLEM), 256);
  V_ID := 'PN-WO-U' || UPPER(SUBSTR(V_KEY, 1, 6));
  SELECT COUNT(*) INTO :V_EXISTING FROM PNEUMORA.OPS.WORK_ORDERS WHERE ORDER_ID = :V_ID;
  IF (V_EXISTING > 0) THEN
    RETURN OBJECT_CONSTRUCT('ok', TRUE, 'order_id', V_ID, 'deduplicated', TRUE);
  END IF;
  INSERT INTO PNEUMORA.OPS.WORK_ORDERS
    (ORDER_ID, WARNING_ID, CREATED_AT, PRIORITY, PROBLEM, ACTION, TECHNICIAN, PART, STATUS, ASSET, NOTE, DATA_ORIGIN)
  VALUES (
    :V_ID, NULLIF(TRIM(:P_SOURCE_KEY), ''), TRY_TO_TIMESTAMP_NTZ(:P_AT), :P_PRIORITY, LEFT(TRIM(:P_PROBLEM), 300),
    LEFT(COALESCE(:P_ACTION, ''), 300), LEFT(COALESCE(:P_TECHNICIAN, ''), 80), LEFT(COALESCE(:P_PART, ''), 80), 'ready', 'APU-01',
    LEFT(COALESCE(NULLIF(TRIM(:P_NOTE), ''), 'Created in PNEUMORA by ' || COALESCE(NULLIF(TRIM(:P_ACTOR), ''), 'UNKNOWN')), 500),
    'OPERATOR_ENTRY'
  );
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'order_id', V_ID, 'deduplicated', FALSE);
END;
$$;

CREATE OR REPLACE PROCEDURE PNEUMORA.OPS.SET_WORK_ORDER_STATUS(
  P_ORDER_ID VARCHAR, P_STATUS VARCHAR, P_NOTE VARCHAR, P_ACTOR VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_FOUND NUMBER;
BEGIN
  IF (P_STATUS IS NULL OR P_STATUS NOT IN ('ready', 'progress', 'parts', 'done', 'dismissed')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Unknown status');
  END IF;
  SELECT COUNT(*) INTO :V_FOUND FROM PNEUMORA.OPS.WORK_ORDERS WHERE ORDER_ID = :P_ORDER_ID;
  IF (V_FOUND = 0) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Work order not found');
  END IF;
  UPDATE PNEUMORA.OPS.WORK_ORDERS
     SET STATUS = :P_STATUS,
         NOTE = IFF(NULLIF(TRIM(:P_NOTE), '') IS NULL, NOTE,
                    LEFT(TRIM(:P_NOTE) || ' (' || COALESCE(NULLIF(TRIM(:P_ACTOR), ''), 'UNKNOWN') || ')', 500))
   WHERE ORDER_ID = :P_ORDER_ID;
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'order_id', P_ORDER_ID, 'status', P_STATUS);
END;
$$;
