/* ============================================================================
   PIADE next-hour heavy-stop risk — leakage-safe production implementation.

   Target: whether the next machine-hour has PCT_DOWNTIME > 0.10.
   Model selection happened offline on two rolling-origin validation periods.
   This file fits only the selected ExtraTrees configuration on all rows before
   2021-12-01 and reports performance only on the untouched final blind period.

   Honest limits:
   - PIADE has five anonymised machines from one site; external validity is
     unknown.
   - Current-hour downtime is a legitimate predictor but makes the model partly
     a sophisticated persistence rule. Baseline metrics are therefore stored
     beside every model metric.
   - The selected model won this finite candidate search; it is not claimed to
     be globally optimal.
   - Scores are operational rankings, not causal failure probabilities.
   ========================================================================== */

USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWCORE_REAL;
USE WAREHOUSE COMPUTE_WH;
ALTER SESSION SET TIMEZONE = 'UTC';
ALTER SESSION SET QUERY_TAG = 'snowcore-real|piade|risk-v2';

/* Feature engineering mirrors scripts/optimize_piade_risk.py exactly:
   162 published numeric columns + 137 engineered columns = 299 features.
   Every lag/window ends at the current row; the only future expression is the
   label, which is excluded from model inputs. */
CREATE OR REPLACE TABLE ML.PLANT_B_FEATURES AS
WITH base AS (
  SELECT
    'PLANT_B:' || EQUIPMENT_ID AS MACHINE_KEY,
    EQUIPMENT_ID AS MACHINE_CODE,
    INTERVAL_START AS HOUR_TS,
    * EXCLUDE (EQUIPMENT_ID, INTERVAL_START, SOURCE_KEY, SOURCE_FILE,
               DATA_ORIGIN, LOAD_TS),
    PCT_PRODUCTION + PCT_PERFORMANCE_LOSS AS RUN_FRAC,
    /* Verified against both sequences_1h_data.csv and sql/11_bronze_load.sql:
       PIADE publishes exactly 130 A_* columns, not 133. Keep the arithmetic
       explicit because this account has not verified object/lambda support. */
    COALESCE(A_028,0)+COALESCE(A_029,0)+COALESCE(A_024,0)+COALESCE(A_045,0)
      +COALESCE(A_001,0)+COALESCE(A_058,0)+COALESCE(A_064,0)+COALESCE(A_030,0)
      +COALESCE(A_101,0)+COALESCE(A_002,0)+COALESCE(A_107,0)+COALESCE(A_056,0)
      +COALESCE(A_015,0)+COALESCE(A_032,0)+COALESCE(A_026,0)+COALESCE(A_003,0)
      +COALESCE(A_008,0)+COALESCE(A_078,0)+COALESCE(A_070,0)+COALESCE(A_004,0)
      +COALESCE(A_005,0)+COALESCE(A_009,0)+COALESCE(A_016,0)+COALESCE(A_010,0)
      +COALESCE(A_027,0)+COALESCE(A_020,0)+COALESCE(A_017,0)+COALESCE(A_048,0)
      +COALESCE(A_022,0)+COALESCE(A_011,0)+COALESCE(A_012,0)+COALESCE(A_013,0)
      +COALESCE(A_042,0)+COALESCE(A_023,0)+COALESCE(A_034,0)+COALESCE(A_036,0)
      +COALESCE(A_079,0)+COALESCE(A_077,0)+COALESCE(A_090,0)+COALESCE(A_021,0)
      +COALESCE(A_049,0)+COALESCE(A_006,0)+COALESCE(A_043,0)+COALESCE(A_051,0)
      +COALESCE(A_106,0)+COALESCE(A_050,0)+COALESCE(A_018,0)+COALESCE(A_102,0)
      +COALESCE(A_031,0)+COALESCE(A_103,0)+COALESCE(A_083,0)+COALESCE(A_081,0)
      +COALESCE(A_074,0)+COALESCE(A_071,0)+COALESCE(A_073,0)+COALESCE(A_104,0)
      +COALESCE(A_084,0)+COALESCE(A_105,0)+COALESCE(A_116,0)+COALESCE(A_128,0)
      +COALESCE(A_109,0)+COALESCE(A_132,0)+COALESCE(A_062,0)+COALESCE(A_131,0)
      +COALESCE(A_035,0)+COALESCE(A_040,0)+COALESCE(A_039,0)+COALESCE(A_055,0)
      +COALESCE(A_127,0)+COALESCE(A_007,0)+COALESCE(A_108,0)+COALESCE(A_037,0)
      +COALESCE(A_119,0)+COALESCE(A_115,0)+COALESCE(A_125,0)+COALESCE(A_124,0)
      +COALESCE(A_130,0)+COALESCE(A_052,0)+COALESCE(A_129,0)+COALESCE(A_019,0)
      +COALESCE(A_126,0)+COALESCE(A_110,0)+COALESCE(A_123,0)+COALESCE(A_114,0)
      +COALESCE(A_120,0)+COALESCE(A_121,0)+COALESCE(A_098,0)+COALESCE(A_095,0)
      +COALESCE(A_087,0)+COALESCE(A_111,0)+COALESCE(A_117,0)+COALESCE(A_044,0)
      +COALESCE(A_122,0)+COALESCE(A_085,0)+COALESCE(A_057,0)+COALESCE(A_066,0)
      +COALESCE(A_112,0)+COALESCE(A_118,0)+COALESCE(A_113,0)+COALESCE(A_093,0)
      +COALESCE(A_041,0)+COALESCE(A_076,0)+COALESCE(A_088,0)+COALESCE(A_097,0)
      +COALESCE(A_065,0)+COALESCE(A_091,0)+COALESCE(A_067,0)+COALESCE(A_068,0)
      +COALESCE(A_033,0)+COALESCE(A_082,0)+COALESCE(A_075,0)+COALESCE(A_099,0)
      +COALESCE(A_086,0)+COALESCE(A_100,0)+COALESCE(A_096,0)+COALESCE(A_094,0)
      +COALESCE(A_089,0)+COALESCE(A_092,0)+COALESCE(A_038,0)+COALESCE(A_080,0)
      +COALESCE(A_069,0)+COALESCE(A_072,0)+COALESCE(A_047,0)+COALESCE(A_059,0)
      +COALESCE(A_046,0)+COALESCE(A_063,0)+COALESCE(A_053,0)+COALESCE(A_054,0)
      +COALESCE(A_060,0)+COALESCE(A_061,0) AS ALARM_TOTAL,
    IFF(COALESCE(A_028,0)>0,1,0)+IFF(COALESCE(A_029,0)>0,1,0)
      +IFF(COALESCE(A_024,0)>0,1,0)+IFF(COALESCE(A_045,0)>0,1,0)
      +IFF(COALESCE(A_001,0)>0,1,0)+IFF(COALESCE(A_058,0)>0,1,0)
      +IFF(COALESCE(A_064,0)>0,1,0)+IFF(COALESCE(A_030,0)>0,1,0)
      +IFF(COALESCE(A_101,0)>0,1,0)+IFF(COALESCE(A_002,0)>0,1,0)
      +IFF(COALESCE(A_107,0)>0,1,0)+IFF(COALESCE(A_056,0)>0,1,0)
      +IFF(COALESCE(A_015,0)>0,1,0)+IFF(COALESCE(A_032,0)>0,1,0)
      +IFF(COALESCE(A_026,0)>0,1,0)+IFF(COALESCE(A_003,0)>0,1,0)
      +IFF(COALESCE(A_008,0)>0,1,0)+IFF(COALESCE(A_078,0)>0,1,0)
      +IFF(COALESCE(A_070,0)>0,1,0)+IFF(COALESCE(A_004,0)>0,1,0)
      +IFF(COALESCE(A_005,0)>0,1,0)+IFF(COALESCE(A_009,0)>0,1,0)
      +IFF(COALESCE(A_016,0)>0,1,0)+IFF(COALESCE(A_010,0)>0,1,0)
      +IFF(COALESCE(A_027,0)>0,1,0)+IFF(COALESCE(A_020,0)>0,1,0)
      +IFF(COALESCE(A_017,0)>0,1,0)+IFF(COALESCE(A_048,0)>0,1,0)
      +IFF(COALESCE(A_022,0)>0,1,0)+IFF(COALESCE(A_011,0)>0,1,0)
      +IFF(COALESCE(A_012,0)>0,1,0)+IFF(COALESCE(A_013,0)>0,1,0)
      +IFF(COALESCE(A_042,0)>0,1,0)+IFF(COALESCE(A_023,0)>0,1,0)
      +IFF(COALESCE(A_034,0)>0,1,0)+IFF(COALESCE(A_036,0)>0,1,0)
      +IFF(COALESCE(A_079,0)>0,1,0)+IFF(COALESCE(A_077,0)>0,1,0)
      +IFF(COALESCE(A_090,0)>0,1,0)+IFF(COALESCE(A_021,0)>0,1,0)
      +IFF(COALESCE(A_049,0)>0,1,0)+IFF(COALESCE(A_006,0)>0,1,0)
      +IFF(COALESCE(A_043,0)>0,1,0)+IFF(COALESCE(A_051,0)>0,1,0)
      +IFF(COALESCE(A_106,0)>0,1,0)+IFF(COALESCE(A_050,0)>0,1,0)
      +IFF(COALESCE(A_018,0)>0,1,0)+IFF(COALESCE(A_102,0)>0,1,0)
      +IFF(COALESCE(A_031,0)>0,1,0)+IFF(COALESCE(A_103,0)>0,1,0)
      +IFF(COALESCE(A_083,0)>0,1,0)+IFF(COALESCE(A_081,0)>0,1,0)
      +IFF(COALESCE(A_074,0)>0,1,0)+IFF(COALESCE(A_071,0)>0,1,0)
      +IFF(COALESCE(A_073,0)>0,1,0)+IFF(COALESCE(A_104,0)>0,1,0)
      +IFF(COALESCE(A_084,0)>0,1,0)+IFF(COALESCE(A_105,0)>0,1,0)
      +IFF(COALESCE(A_116,0)>0,1,0)+IFF(COALESCE(A_128,0)>0,1,0)
      +IFF(COALESCE(A_109,0)>0,1,0)+IFF(COALESCE(A_132,0)>0,1,0)
      +IFF(COALESCE(A_062,0)>0,1,0)+IFF(COALESCE(A_131,0)>0,1,0)
      +IFF(COALESCE(A_035,0)>0,1,0)+IFF(COALESCE(A_040,0)>0,1,0)
      +IFF(COALESCE(A_039,0)>0,1,0)+IFF(COALESCE(A_055,0)>0,1,0)
      +IFF(COALESCE(A_127,0)>0,1,0)+IFF(COALESCE(A_007,0)>0,1,0)
      +IFF(COALESCE(A_108,0)>0,1,0)+IFF(COALESCE(A_037,0)>0,1,0)
      +IFF(COALESCE(A_119,0)>0,1,0)+IFF(COALESCE(A_115,0)>0,1,0)
      +IFF(COALESCE(A_125,0)>0,1,0)+IFF(COALESCE(A_124,0)>0,1,0)
      +IFF(COALESCE(A_130,0)>0,1,0)+IFF(COALESCE(A_052,0)>0,1,0)
      +IFF(COALESCE(A_129,0)>0,1,0)+IFF(COALESCE(A_019,0)>0,1,0)
      +IFF(COALESCE(A_126,0)>0,1,0)+IFF(COALESCE(A_110,0)>0,1,0)
      +IFF(COALESCE(A_123,0)>0,1,0)+IFF(COALESCE(A_114,0)>0,1,0)
      +IFF(COALESCE(A_120,0)>0,1,0)+IFF(COALESCE(A_121,0)>0,1,0)
      +IFF(COALESCE(A_098,0)>0,1,0)+IFF(COALESCE(A_095,0)>0,1,0)
      +IFF(COALESCE(A_087,0)>0,1,0)+IFF(COALESCE(A_111,0)>0,1,0)
      +IFF(COALESCE(A_117,0)>0,1,0)+IFF(COALESCE(A_044,0)>0,1,0)
      +IFF(COALESCE(A_122,0)>0,1,0)+IFF(COALESCE(A_085,0)>0,1,0)
      +IFF(COALESCE(A_057,0)>0,1,0)+IFF(COALESCE(A_066,0)>0,1,0)
      +IFF(COALESCE(A_112,0)>0,1,0)+IFF(COALESCE(A_118,0)>0,1,0)
      +IFF(COALESCE(A_113,0)>0,1,0)+IFF(COALESCE(A_093,0)>0,1,0)
      +IFF(COALESCE(A_041,0)>0,1,0)+IFF(COALESCE(A_076,0)>0,1,0)
      +IFF(COALESCE(A_088,0)>0,1,0)+IFF(COALESCE(A_097,0)>0,1,0)
      +IFF(COALESCE(A_065,0)>0,1,0)+IFF(COALESCE(A_091,0)>0,1,0)
      +IFF(COALESCE(A_067,0)>0,1,0)+IFF(COALESCE(A_068,0)>0,1,0)
      +IFF(COALESCE(A_033,0)>0,1,0)+IFF(COALESCE(A_082,0)>0,1,0)
      +IFF(COALESCE(A_075,0)>0,1,0)+IFF(COALESCE(A_099,0)>0,1,0)
      +IFF(COALESCE(A_086,0)>0,1,0)+IFF(COALESCE(A_100,0)>0,1,0)
      +IFF(COALESCE(A_096,0)>0,1,0)+IFF(COALESCE(A_094,0)>0,1,0)
      +IFF(COALESCE(A_089,0)>0,1,0)+IFF(COALESCE(A_092,0)>0,1,0)
      +IFF(COALESCE(A_038,0)>0,1,0)+IFF(COALESCE(A_080,0)>0,1,0)
      +IFF(COALESCE(A_069,0)>0,1,0)+IFF(COALESCE(A_072,0)>0,1,0)
      +IFF(COALESCE(A_047,0)>0,1,0)+IFF(COALESCE(A_059,0)>0,1,0)
      +IFF(COALESCE(A_046,0)>0,1,0)+IFF(COALESCE(A_063,0)>0,1,0)
      +IFF(COALESCE(A_053,0)>0,1,0)+IFF(COALESCE(A_054,0)>0,1,0)
      +IFF(COALESCE(A_060,0)>0,1,0)+IFF(COALESCE(A_061,0)>0,1,0)
      AS ALARM_DISTINCT,
    /* The 25 transition columns are retained individually and also summed. */
    TRANS_IDLE_TO_IDLE + TRANS_IDLE_TO_PRODUCTION + TRANS_IDLE_TO_DOWNTIME
      + TRANS_IDLE_TO_PERFORMANCE_LOSS + TRANS_IDLE_TO_SCHEDULED_DOWNTIME
      + TRANS_PRODUCTION_TO_IDLE + TRANS_PRODUCTION_TO_PRODUCTION
      + TRANS_PRODUCTION_TO_DOWNTIME + TRANS_PRODUCTION_TO_PERFORMANCE_LOSS
      + TRANS_PRODUCTION_TO_SCHEDULED_DOWNTIME + TRANS_DOWNTIME_TO_IDLE
      + TRANS_DOWNTIME_TO_PRODUCTION + TRANS_DOWNTIME_TO_DOWNTIME
      + TRANS_DOWNTIME_TO_PERFORMANCE_LOSS + TRANS_DOWNTIME_TO_SCHEDULED_DOWNTIME
      + TRANS_PERFORMANCE_LOSS_TO_IDLE + TRANS_PERFORMANCE_LOSS_TO_PRODUCTION
      + TRANS_PERFORMANCE_LOSS_TO_DOWNTIME + TRANS_PERFORMANCE_LOSS_TO_PERFORMANCE_LOSS
      + TRANS_PERFORMANCE_LOSS_TO_SCHEDULED_DOWNTIME
      + TRANS_SCHEDULED_DOWNTIME_TO_IDLE + TRANS_SCHEDULED_DOWNTIME_TO_PRODUCTION
      + TRANS_SCHEDULED_DOWNTIME_TO_DOWNTIME
      + TRANS_SCHEDULED_DOWNTIME_TO_PERFORMANCE_LOSS
      + TRANS_SCHEDULED_DOWNTIME_TO_SCHEDULED_DOWNTIME AS TRANSITION_TOTAL
  FROM BRONZE.PIADE_HOURLY_RAW
),
heavy_group AS (
  SELECT b.*,
    SUM(IFF(PCT_DOWNTIME > 0.10, 1, 0)) OVER (
      PARTITION BY MACHINE_KEY ORDER BY HOUR_TS
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS HEAVY_GROUP
  FROM base b
),
history AS (
  SELECT h.*,
    /* Seven history sources x five means. */
    AVG(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MEAN_3,
    AVG(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MEAN_6,
    AVG(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MEAN_12,
    AVG(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MEAN_24,
    AVG(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MEAN_72,
    AVG(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MEAN_3,
    AVG(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MEAN_6,
    AVG(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MEAN_12,
    AVG(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MEAN_24,
    AVG(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MEAN_72,
    AVG(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MEAN_3,
    AVG(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MEAN_6,
    AVG(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MEAN_12,
    AVG(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MEAN_24,
    AVG(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MEAN_72,
    AVG(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MEAN_3,
    AVG(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MEAN_6,
    AVG(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MEAN_12,
    AVG(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MEAN_24,
    AVG(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MEAN_72,
    AVG(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MEAN_3,
    AVG(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MEAN_6,
    AVG(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MEAN_12,
    AVG(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MEAN_24,
    AVG(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MEAN_72,
    AVG(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MEAN_3,
    AVG(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MEAN_6,
    AVG(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MEAN_12,
    AVG(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MEAN_24,
    AVG(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MEAN_72,
    AVG(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MEAN_3,
    AVG(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MEAN_6,
    AVG(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MEAN_12,
    AVG(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MEAN_24,
    AVG(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MEAN_72,

    /* Max and sample standard deviation at 12/24/72 hours, matching pandas rolling.std(). */
    MAX(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MAX_12,
    MAX(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MAX_24,
    MAX(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_MAX_72,
    STDDEV_SAMP(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_STD_12,
    STDDEV_SAMP(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_STD_24,
    STDDEV_SAMP(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS PCT_DOWNTIME_STD_72,
    MAX(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MAX_12,
    MAX(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MAX_24,
    MAX(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS PCT_IDLE_MAX_72,
    STDDEV_SAMP(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS PCT_IDLE_STD_12,
    STDDEV_SAMP(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS PCT_IDLE_STD_24,
    STDDEV_SAMP(PCT_IDLE) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS PCT_IDLE_STD_72,
    MAX(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MAX_12,
    MAX(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MAX_24,
    MAX(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS RUN_FRAC_MAX_72,
    STDDEV_SAMP(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS RUN_FRAC_STD_12,
    STDDEV_SAMP(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS RUN_FRAC_STD_24,
    STDDEV_SAMP(RUN_FRAC) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS RUN_FRAC_STD_72,
    MAX(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MAX_12,
    MAX(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MAX_24,
    MAX(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_MAX_72,
    STDDEV_SAMP(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_STD_12,
    STDDEV_SAMP(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_STD_24,
    STDDEV_SAMP(ALARM_TOTAL) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS ALARM_TOTAL_STD_72,
    MAX(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MAX_12,
    MAX(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MAX_24,
    MAX(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_MAX_72,
    STDDEV_SAMP(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_STD_12,
    STDDEV_SAMP(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_STD_24,
    STDDEV_SAMP(ALARM_DISTINCT) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS ALARM_DISTINCT_STD_72,
    MAX(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MAX_12,
    MAX(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MAX_24,
    MAX(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_MAX_72,
    STDDEV_SAMP(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_STD_12,
    STDDEV_SAMP(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_STD_24,
    STDDEV_SAMP(STATE_CHANGES) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS STATE_CHANGES_STD_72,
    MAX(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MAX_12,
    MAX(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MAX_24,
    MAX(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS COUNT_SUM_MAX_72,
    STDDEV_SAMP(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS COUNT_SUM_STD_12,
    STDDEV_SAMP(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS COUNT_SUM_STD_24,
    STDDEV_SAMP(COUNT_SUM) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW) AS COUNT_SUM_STD_72,

    /* Seven sources x six strictly historical lags. */
    LAG(PCT_DOWNTIME,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_DOWNTIME_LAG_1,
    LAG(PCT_DOWNTIME,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_DOWNTIME_LAG_2,
    LAG(PCT_DOWNTIME,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_DOWNTIME_LAG_3,
    LAG(PCT_DOWNTIME,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_DOWNTIME_LAG_6,
    LAG(PCT_DOWNTIME,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_DOWNTIME_LAG_12,
    LAG(PCT_DOWNTIME,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_DOWNTIME_LAG_24,
    LAG(PCT_IDLE,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_IDLE_LAG_1,
    LAG(PCT_IDLE,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_IDLE_LAG_2,
    LAG(PCT_IDLE,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_IDLE_LAG_3,
    LAG(PCT_IDLE,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_IDLE_LAG_6,
    LAG(PCT_IDLE,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_IDLE_LAG_12,
    LAG(PCT_IDLE,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS PCT_IDLE_LAG_24,
    LAG(RUN_FRAC,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS RUN_FRAC_LAG_1,
    LAG(RUN_FRAC,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS RUN_FRAC_LAG_2,
    LAG(RUN_FRAC,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS RUN_FRAC_LAG_3,
    LAG(RUN_FRAC,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS RUN_FRAC_LAG_6,
    LAG(RUN_FRAC,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS RUN_FRAC_LAG_12,
    LAG(RUN_FRAC,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS RUN_FRAC_LAG_24,
    LAG(ALARM_TOTAL,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_TOTAL_LAG_1,
    LAG(ALARM_TOTAL,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_TOTAL_LAG_2,
    LAG(ALARM_TOTAL,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_TOTAL_LAG_3,
    LAG(ALARM_TOTAL,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_TOTAL_LAG_6,
    LAG(ALARM_TOTAL,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_TOTAL_LAG_12,
    LAG(ALARM_TOTAL,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_TOTAL_LAG_24,
    LAG(ALARM_DISTINCT,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_DISTINCT_LAG_1,
    LAG(ALARM_DISTINCT,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_DISTINCT_LAG_2,
    LAG(ALARM_DISTINCT,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_DISTINCT_LAG_3,
    LAG(ALARM_DISTINCT,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_DISTINCT_LAG_6,
    LAG(ALARM_DISTINCT,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_DISTINCT_LAG_12,
    LAG(ALARM_DISTINCT,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS ALARM_DISTINCT_LAG_24,
    LAG(STATE_CHANGES,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS STATE_CHANGES_LAG_1,
    LAG(STATE_CHANGES,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS STATE_CHANGES_LAG_2,
    LAG(STATE_CHANGES,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS STATE_CHANGES_LAG_3,
    LAG(STATE_CHANGES,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS STATE_CHANGES_LAG_6,
    LAG(STATE_CHANGES,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS STATE_CHANGES_LAG_12,
    LAG(STATE_CHANGES,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS STATE_CHANGES_LAG_24,
    LAG(COUNT_SUM,1) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS COUNT_SUM_LAG_1,
    LAG(COUNT_SUM,2) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS COUNT_SUM_LAG_2,
    LAG(COUNT_SUM,3) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS COUNT_SUM_LAG_3,
    LAG(COUNT_SUM,6) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS COUNT_SUM_LAG_6,
    LAG(COUNT_SUM,12) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS COUNT_SUM_LAG_12,
    LAG(COUNT_SUM,24) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS COUNT_SUM_LAG_24,
    ROW_NUMBER() OVER (PARTITION BY MACHINE_KEY, HEAVY_GROUP ORDER BY HOUR_TS) - 1
      AS HOURS_SINCE_HEAVY_STOP,
    COALESCE(DATEDIFF('hour', LAG(HOUR_TS) OVER (
      PARTITION BY MACHINE_KEY ORDER BY HOUR_TS), HOUR_TS), -1) AS GAP_HOURS
  FROM heavy_group h
),
labeled AS (
  SELECT h.*,
    PCT_DOWNTIME_MEAN_3 - PCT_DOWNTIME_MEAN_24 AS DOWNTIME_ACCEL_3_24,
    RUN_FRAC_MEAN_3 - RUN_FRAC_MEAN_24 AS RUN_ACCEL_3_24,
    ALARM_TOTAL_MEAN_3 - ALARM_TOTAL_MEAN_24 AS ALARM_ACCEL_3_24,
    SIN(2 * PI() * DATE_PART('hour', HOUR_TS) / 24) AS HOUR_SIN,
    COS(2 * PI() * DATE_PART('hour', HOUR_TS) / 24) AS HOUR_COS,
    /* pandas dayofweek used by the offline search is Monday=0. */
    SIN(2 * PI() * (DAYOFWEEKISO(HOUR_TS)-1) / 7) AS DOW_SIN,
    COS(2 * PI() * (DAYOFWEEKISO(HOUR_TS)-1) / 7) AS DOW_COS,
    IFF(MACHINE_CODE='s_1',1,0) AS MACHINE_S_1,
    IFF(MACHINE_CODE='s_2',1,0) AS MACHINE_S_2,
    IFF(MACHINE_CODE='s_3',1,0) AS MACHINE_S_3,
    IFF(MACHINE_CODE='s_4',1,0) AS MACHINE_S_4,
    IFF(MACHINE_CODE='s_5',1,0) AS MACHINE_S_5,
    LEAD(PCT_DOWNTIME) OVER (PARTITION BY MACHINE_KEY ORDER BY HOUR_TS) AS NEXT_HOUR_DOWNTIME
  FROM history h
)
SELECT
  HASH(MACHINE_KEY || '|' || TO_CHAR(HOUR_TS,'YYYY-MM-DD HH24:MI:SS.FF9')) AS ROW_ID,
  MACHINE_KEY, MACHINE_CODE, HOUR_TS,
  l.* EXCLUDE (MACHINE_KEY, MACHINE_CODE, HOUR_TS, HEAVY_GROUP,
               NEXT_HOUR_DOWNTIME),
  PCT_DOWNTIME AS BASELINE_SCORE,
  IFF(NEXT_HOUR_DOWNTIME > 0.10, 1, 0) AS LABEL_HEAVY_STOP,
  NEXT_HOUR_DOWNTIME,
  IFF(HOUR_TS < '2021-12-01'::TIMESTAMP_NTZ, 'TRAIN', 'FINAL_BLIND_TEST') AS SPLIT_PART,
  'DERIVED_FROM_OBSERVED' AS DATA_ORIGIN
FROM labeled l
WHERE NEXT_HOUR_DOWNTIME IS NOT NULL;

COMMENT ON TABLE ML.PLANT_B_FEATURES IS
  'Leakage-safe 299-feature PIADE hourly store. Final blind test starts 2021-12-01; model scores are emitted only for that period.';

CREATE OR REPLACE PROCEDURE ML.TRAIN_PLANT_B_RISK()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python','scikit-learn','pandas','numpy','pyarrow')
HANDLER = 'run'
EXECUTE AS CALLER
AS
$$
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import average_precision_score, roc_auc_score

SEED = 20260925
FINAL_TEST_START = pd.Timestamp("2021-12-01")
NOT_FEATURES = {
    "ROW_ID","MACHINE_KEY","MACHINE_CODE","HOUR_TS","SPLIT_PART","DATA_ORIGIN",
    "LABEL_HEAVY_STOP","NEXT_HOUR_DOWNTIME","BASELINE_SCORE",
}

def exact_fraction(y, score, machine, hour, fraction=0.10):
    """Exactly ceil(n*fraction) rows; deterministic tie break, no inflation."""
    order = pd.DataFrame({
        "score": np.asarray(score, dtype=float),
        "machine": machine.astype(str).to_numpy(),
        "hour": pd.to_datetime(hour).astype("int64").to_numpy(),
        "position": np.arange(len(y)),
    }).sort_values(
        ["score","machine","hour"], ascending=[False,True,True], kind="mergesort"
    )["position"].to_numpy()
    take = max(1, int(np.ceil(len(order) * fraction)))
    selected = order[:take]
    yy = np.asarray(y, dtype=int)
    hits = int(yy[selected].sum())
    return selected, hits / take, hits / int(yy.sum()) if yy.sum() else 0.0

def safe_metrics(y, score):
    if pd.Series(y).nunique() < 2:
        return None, None
    return float(roc_auc_score(y, score)), float(average_precision_score(y, score))

def run(session):
    df = session.table("ML.PLANT_B_FEATURES").to_pandas()
    df = df.sort_values(["MACHINE_CODE","HOUR_TS"], kind="mergesort").reset_index(drop=True)
    # Preserve the exact feature order used by the offline search. ExtraTrees
    # samples feature indices, so merely having the same set in another order
    # is not sufficient for a reproducible selected model.
    derived = ["RUN_FRAC","ALARM_TOTAL","ALARM_DISTINCT","TRANSITION_TOTAL"]
    history = []
    for source in [
        "PCT_DOWNTIME","PCT_IDLE","RUN_FRAC","ALARM_TOTAL",
        "ALARM_DISTINCT","STATE_CHANGES","COUNT_SUM",
    ]:
        for window in (3,6,12,24,72):
            history.append(f"{source}_MEAN_{window}")
            if window in (12,24,72):
                history.extend([f"{source}_MAX_{window}",f"{source}_STD_{window}"])
        history.extend([f"{source}_LAG_{lag}" for lag in (1,2,3,6,12,24)])
    extras = [
        "DOWNTIME_ACCEL_3_24","RUN_ACCEL_3_24","ALARM_ACCEL_3_24",
        "HOURS_SINCE_HEAVY_STOP","GAP_HOURS",
        "HOUR_SIN","HOUR_COS","DOW_SIN","DOW_COS",
        "MACHINE_S_1","MACHINE_S_2","MACHINE_S_3","MACHINE_S_4","MACHINE_S_5",
    ]
    engineered = set(derived + history + extras)
    source = [c for c in df.columns if c not in NOT_FEATURES
              and c not in engineered and pd.api.types.is_numeric_dtype(df[c])]
    features = source + derived + history + extras
    if len(features) != 299:
        raise ValueError(f"Feature contract drift: expected 299 numeric features, got {len(features)}")
    df[features] = df[features].replace([np.inf,-np.inf], np.nan).fillna(0)
    train = df[df["HOUR_TS"] < FINAL_TEST_START]
    test = df[df["HOUR_TS"] >= FINAL_TEST_START].copy()
    if train.empty or test.empty:
        raise ValueError("Chronological train/final-blind-test split produced an empty partition")

    model = ExtraTreesClassifier(
        n_estimators=700, max_features=0.4, min_samples_leaf=30,
        class_weight="balanced", n_jobs=-1, random_state=SEED,
    )
    model.fit(train[features], train["LABEL_HEAVY_STOP"].astype(int))
    test["RISK_SCORE"] = model.predict_proba(test[features])[:, 1]

    chosen, _, _ = exact_fraction(
        test["LABEL_HEAVY_STOP"], test["RISK_SCORE"],
        test["MACHINE_CODE"], test["HOUR_TS"])
    test["IS_FLAGGED"] = 0
    test.iloc[chosen, test.columns.get_loc("IS_FLAGGED")] = 1
    # Equal-workload rank bands remain meaningful if raw probabilities shift.
    rank = test[["RISK_SCORE","MACHINE_CODE","HOUR_TS"]].sort_values(
        ["RISK_SCORE","MACHINE_CODE","HOUR_TS"],
        ascending=[True,True,True], kind="mergesort").index
    percentile = pd.Series(np.arange(1, len(test)+1) / len(test), index=rank)
    test["RISK_PERCENTILE"] = test.index.map(percentile)
    test["RISK_BAND"] = pd.cut(
        test["RISK_PERCENTILE"], bins=[0,0.25,0.50,0.75,1.0],
        labels=["LOW","MODERATE","ELEVATED","HIGH"], include_lowest=True).astype(str)

    score_cols = [
        "ROW_ID","MACHINE_KEY","MACHINE_CODE","HOUR_TS","RISK_SCORE",
        "RISK_PERCENTILE","RISK_BAND","IS_FLAGGED","BASELINE_SCORE",
        "LABEL_HEAVY_STOP","NEXT_HOUR_DOWNTIME",
    ]
    scores = test[score_cols].copy()
    scores["SCORE_PERIOD"] = "FINAL_BLIND_TEST"
    scores["BLIND_TEST_START"] = FINAL_TEST_START
    scores["DATA_ORIGIN"] = "DERIVED_FROM_OBSERVED"
    session.write_pandas(scores, "PLANT_B_RISK_SCORE", schema="ML",
                         auto_create_table=True, overwrite=True, quote_identifiers=False)

    metric_rows = []
    for scope, grp in [("FLEET", test)] + list(test.groupby("MACHINE_CODE", sort=True)):
        y = grp["LABEL_HEAVY_STOP"].astype(int)
        model_auc, model_ap = safe_metrics(y, grp["RISK_SCORE"])
        base_auc, base_ap = safe_metrics(y, grp["BASELINE_SCORE"])
        _, mp, mr = exact_fraction(y, grp["RISK_SCORE"], grp["MACHINE_CODE"], grp["HOUR_TS"])
        _, bp, br = exact_fraction(y, grp["BASELINE_SCORE"], grp["MACHINE_CODE"], grp["HOUR_TS"])
        metric_rows.append({
            "SCOPE": scope, "TEST_ROWS": int(len(grp)), "BASE_RATE": float(y.mean()),
            "AUC": model_auc, "AVG_PRECISION": model_ap,
            "TOP_DECILE_PRECISION": mp, "TOP_DECILE_RECALL": mr,
            "BASELINE_AUC": base_auc, "BASELINE_AVG_PRECISION": base_ap,
            "BASELINE_TOP_DECILE_PRECISION": bp,
            "BASELINE_TOP_DECILE_RECALL": br,
            "TOP_DECILE_ROWS": int(np.ceil(len(grp)*0.10)),
        })
    metrics = pd.DataFrame(metric_rows)
    metrics["TRAIN_ROWS"] = int(len(train))
    metrics["FEATURE_COUNT"] = len(features)
    metrics["TARGET"] = "next machine-hour PCT_DOWNTIME > 0.10"
    metrics["MODEL"] = "sklearn ExtraTreesClassifier"
    metrics["MODEL_CONFIG"] = "n_estimators=700,max_features=0.4,min_samples_leaf=30,class_weight=balanced"
    metrics["SELECTION_METHOD"] = "offline rolling-origin search; final blind period excluded from selection"
    metrics["TRAIN_END_EXCLUSIVE"] = FINAL_TEST_START
    metrics["BLIND_TEST_START"] = FINAL_TEST_START
    metrics["BLIND_TEST_END"] = pd.to_datetime(test["HOUR_TS"]).max()
    metrics["SEED"] = SEED
    metrics["CAVEAT"] = "Single anonymised five-machine site; partly persistence; ranking is not causal and optimality is not claimed."
    metrics["TRAINED_AT"] = pd.Timestamp.utcnow().tz_localize(None)
    session.write_pandas(metrics, "PLANT_B_MODEL_METRICS", schema="ML",
                         auto_create_table=True, overwrite=True, quote_identifiers=False)

    importance = pd.DataFrame({
        "FEATURE": features,
        "IMPORTANCE": model.feature_importances_.astype(float),
    }).sort_values(["IMPORTANCE","FEATURE"], ascending=[False,True]).reset_index(drop=True)
    importance["RANK"] = np.arange(1, len(importance)+1)
    importance["MODEL"] = "ExtraTreesClassifier"
    importance["BLIND_TEST_START"] = FINAL_TEST_START
    session.write_pandas(importance, "PLANT_B_FEATURE_IMPORTANCE", schema="ML",
                         auto_create_table=True, overwrite=True, quote_identifiers=False)

    calibration = test.groupby("RISK_BAND", observed=True).agg(
        HOURS=("ROW_ID","size"), MEAN_SCORE=("RISK_SCORE","mean"),
        MIN_SCORE=("RISK_SCORE","min"), MAX_SCORE=("RISK_SCORE","max"),
        ACTUAL_RATE=("LABEL_HEAVY_STOP","mean"),
    ).reset_index()
    calibration["BANDING_METHOD"] = "final-blind-test score rank quartiles"
    session.write_pandas(calibration, "PLANT_B_CALIBRATION_BAND", schema="ML",
                         auto_create_table=True, overwrite=True, quote_identifiers=False)
    return {
        "model": "extra_leaf30_mf04", "features": len(features),
        "train_rows": int(len(train)), "blind_test_rows": int(len(test)),
        "blind_test_start": str(FINAL_TEST_START.date()),
        "scores_are_blind_test_only": True,
    }
$$;

CALL ML.TRAIN_PLANT_B_RISK();

/* Contract and leakage checks. */
SELECT SPLIT_PART, COUNT(*) ROWS, MIN(HOUR_TS) FIRST_HOUR, MAX(HOUR_TS) LAST_HOUR,
       AVG(LABEL_HEAVY_STOP) POSITIVE_RATE
FROM ML.PLANT_B_FEATURES GROUP BY SPLIT_PART ORDER BY FIRST_HOUR;

SELECT COUNT(*)-COUNT(DISTINCT ROW_ID) AS DUPLICATE_FEATURE_ROW_IDS
FROM ML.PLANT_B_FEATURES;

SELECT COUNT(*) AS SCORED_ROWS,
       /* write_pandas persists this pandas timestamp as epoch nanoseconds on
          this account; normalize it before comparing with a timestamp. */
       COUNT_IF(TO_TIMESTAMP_NTZ(HOUR_TS/1000000000)
                < '2021-12-01'::TIMESTAMP_NTZ) AS NON_BLIND_SCORES,
       COUNT_IF(SCORE_PERIOD <> 'FINAL_BLIND_TEST') AS WRONG_PERIOD_LABELS,
       SUM(IS_FLAGGED) AS FLAGGED_ROWS,
       CEIL(COUNT(*) * 0.10) AS EXPECTED_FLAGGED_ROWS
FROM ML.PLANT_B_RISK_SCORE;

SELECT SCOPE, TEST_ROWS, BASE_RATE, AUC, AVG_PRECISION,
       TOP_DECILE_PRECISION, TOP_DECILE_RECALL,
       BASELINE_AUC, BASELINE_AVG_PRECISION,
       BASELINE_TOP_DECILE_PRECISION, BASELINE_TOP_DECILE_RECALL,
       FEATURE_COUNT, BLIND_TEST_START, BLIND_TEST_END, CAVEAT
FROM ML.PLANT_B_MODEL_METRICS
ORDER BY IFF(SCOPE='FLEET',0,1), SCOPE;

SELECT * FROM ML.PLANT_B_CALIBRATION_BAND ORDER BY MIN_SCORE;
SELECT RANK, FEATURE, IMPORTANCE FROM ML.PLANT_B_FEATURE_IMPORTANCE ORDER BY RANK LIMIT 20;
