/* ============================================================================
   PIADE-only synthetic ERP and digital thread.

   All ERP identities, stock, prices and euros are scenarios, not source facts.
   Every row is deterministically anchored to observed or derived PIADE data.
   Cause codes are anonymised; material names deliberately do not assert a
   component identity. No CoMoPI object is referenced.
   ========================================================================== */
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWCORE_REAL;
USE WAREHOUSE COMPUTE_WH;
ALTER SESSION SET TIMEZONE = 'UTC';
ALTER SESSION SET QUERY_TAG = 'snowcore-real|piade|erp';

/* Preserve rows created by sql/16_it_synthetic.sql. */
MERGE INTO GOLD.IT_ASSUMPTION t
USING (
  SELECT * FROM VALUES
    ('AS-PIADE-ERP-2026-09-25','PLANT_B','ERP_MARGIN_PER_PACKAGE',0.18,'EUR/package',FALSE,
     'Scenario only. PIADE records packages but no revenue, margin or currency.'),
    ('AS-PIADE-ERP-2026-09-25','PLANT_B','ERP_REORDER_DAYS',14,'days',FALSE,
     'Scenario only. Used to convert deterministic daily demand into a reorder point.'),
    ('AS-PIADE-ERP-2026-09-25','PLANT_B','ERP_LEAD_TIME_MIN_DAYS',2,'days',FALSE,
     'Scenario lower bound; no supplier or lead-time data exists in PIADE.'),
    ('AS-PIADE-ERP-2026-09-25','PLANT_B','ERP_LEAD_TIME_MAX_DAYS',14,'days',FALSE,
     'Scenario upper bound; selected deterministically by material hash.'),
    ('AS-PIADE-ERP-2026-09-25','PLANT_B','ERP_STOCK_COVER_MULTIPLIER',1.50,'fraction',FALSE,
     'Scenario on-hand is deterministic around 1.5 times reorder point.')
  v(ASSUMPTION_SET_ID,PLANT_SCOPE,NAME,VALUE,UNIT,IS_MEASURED,BASIS)
) s
ON t.ASSUMPTION_SET_ID=s.ASSUMPTION_SET_ID AND t.PLANT_SCOPE=s.PLANT_SCOPE AND t.NAME=s.NAME
WHEN NOT MATCHED THEN INSERT
  (ASSUMPTION_SET_ID,PLANT_SCOPE,NAME,VALUE,UNIT,IS_MEASURED,BASIS)
VALUES
  (s.ASSUMPTION_SET_ID,s.PLANT_SCOPE,s.NAME,s.VALUE,s.UNIT,s.IS_MEASURED,s.BASIS);

/* Retire the superseded uplift row if an earlier draft was ever run. No
   assumption from sql/16_it_synthetic.sql is touched. */
DELETE FROM GOLD.IT_ASSUMPTION
WHERE ASSUMPTION_SET_ID='AS-PIADE-ERP-2026-09-25'
  AND PLANT_SCOPE='PLANT_B'
  AND NAME='ERP_TARGET_UPLIFT';

/* One generic service-kit material per anonymised PIADE cause that actually
   consumed parts. MATERIAL_NAME does not invent a bearing, motor or other
   component that the source cannot identify. */
CREATE OR REPLACE TABLE GOLD.DIM_MATERIAL AS
WITH used_causes AS (
  SELECT CAUSE_CODE, COUNT(*) AS ANCHORED_WORK_ORDERS,
         SUM(PARTS_COST) AS ANCHORED_PARTS_COST
  FROM GOLD.WORK_ORDER
  WHERE PLANT_CODE='PLANT_B' AND PARTS_COST > 0
  GROUP BY CAUSE_CODE
)
SELECT
  'MAT-B-' || CAUSE_CODE AS MATERIAL_ID,
  CAUSE_CODE AS ANONYMIZED_CAUSE_CODE,
  'Service kit for anonymized cause ' || CAUSE_CODE AS MATERIAL_NAME,
  'Generic scenario kit only; PIADE does not disclose component identity.' AS MATERIAL_LIMITATION,
  ANCHORED_WORK_ORDERS,
  ROUND(ANCHORED_PARTS_COST,2) AS ANCHORED_PARTS_COST,
  'SYNTHETIC_ERP' AS DATA_ORIGIN,
  'Observed PIADE breakdown work orders with non-zero deterministic parts cost' AS SOURCE_ANCHOR,
  'AS-PIADE-ERP-2026-09-25' AS ASSUMPTION_SET_ID
FROM used_causes;

/* Exactly one part row for each Plant B work order with PARTS_COST > 0.
   Quantity is deterministic; EXTENDED_COST reconciles exactly to WORK_ORDER. */
CREATE OR REPLACE TABLE GOLD.WORK_ORDER_PART AS
SELECT
  w.WORK_ORDER_ID || '-P01' AS WORK_ORDER_PART_ID,
  w.WORK_ORDER_ID,
  m.MATERIAL_ID,
  1 + (ABS(HASH(w.WORK_ORDER_ID || '|quantity')) % 3) AS QUANTITY,
  ROUND(w.PARTS_COST /
    (1 + (ABS(HASH(w.WORK_ORDER_ID || '|quantity')) % 3)), 6) AS UNIT_COST_EUR,
  w.PARTS_COST AS EXTENDED_COST_EUR,
  w.MACHINE_KEY,
  w.SOURCE_EVENT_START,
  'SYNTHETIC_ERP' AS DATA_ORIGIN,
  'Plant B work order anchored to observed PIADE breakdown' AS SOURCE_ANCHOR,
  'AS-PIADE-ERP-2026-09-25' AS ASSUMPTION_SET_ID
FROM GOLD.WORK_ORDER w
JOIN GOLD.DIM_MATERIAL m ON m.ANONYMIZED_CAUSE_CODE=w.CAUSE_CODE
WHERE w.PLANT_CODE='PLANT_B' AND w.PARTS_COST > 0;

/* One deterministic inventory scenario per material. Demand is anchored to
   actual synthetic part consumption; no unused catalogue rows are invented. */
CREATE OR REPLACE TABLE GOLD.INVENTORY_SNAPSHOT AS
WITH cfg AS (
  SELECT
    MAX(IFF(NAME='ERP_REORDER_DAYS',VALUE,NULL)) REORDER_DAYS,
    MAX(IFF(NAME='ERP_STOCK_COVER_MULTIPLIER',VALUE,NULL)) STOCK_COVER_MULTIPLIER
  FROM GOLD.IT_ASSUMPTION
  WHERE ASSUMPTION_SET_ID='AS-PIADE-ERP-2026-09-25'
), demand AS (
  SELECT p.MATERIAL_ID, SUM(p.QUANTITY) AS LIFETIME_QTY,
         COUNT(DISTINCT TO_DATE(p.SOURCE_EVENT_START)) AS DEMAND_DAYS,
         MIN(TO_DATE(p.SOURCE_EVENT_START)) AS FIRST_DEMAND_DATE,
         MAX(TO_DATE(p.SOURCE_EVENT_START)) AS SNAPSHOT_DATE
  FROM GOLD.WORK_ORDER_PART p GROUP BY p.MATERIAL_ID
),
calc AS (
  SELECT d.*,c.STOCK_COVER_MULTIPLIER,
    GREATEST(1,CEIL(d.LIFETIME_QTY
      / NULLIF(DATEDIFF('day',d.FIRST_DEMAND_DATE,d.SNAPSHOT_DATE)+1,0)
      * c.REORDER_DAYS))
      AS REORDER_POINT,
    2 + (ABS(HASH(d.MATERIAL_ID || '|lead')) % 13) AS LEAD_TIME_DAYS
  FROM demand d CROSS JOIN cfg c
)
SELECT
  'INV-' || MATERIAL_ID || '-' || TO_CHAR(SNAPSHOT_DATE,'YYYYMMDD') AS INVENTORY_SNAPSHOT_ID,
  MATERIAL_ID, SNAPSHOT_DATE,
  FLOOR(REORDER_POINT * (STOCK_COVER_MULTIPLIER - 1.0
    + (ABS(HASH(MATERIAL_ID || '|onhand')) % 201)/100.0)) AS ON_HAND_QTY,
  REORDER_POINT,
  LEAD_TIME_DAYS,
  CASE
    WHEN FLOOR(REORDER_POINT * (STOCK_COVER_MULTIPLIER - 1.0
      + (ABS(HASH(MATERIAL_ID || '|onhand')) % 201)/100.0))=0 THEN 'STOCKOUT'
    WHEN FLOOR(REORDER_POINT * (STOCK_COVER_MULTIPLIER - 1.0
      + (ABS(HASH(MATERIAL_ID || '|onhand')) % 201)/100.0))<=REORDER_POINT THEN 'REORDER'
    ELSE 'HEALTHY'
  END AS STOCK_STATE,
  LIFETIME_QTY AS ANCHORED_CONSUMPTION_QTY,
  DEMAND_DAYS AS ANCHORED_DEMAND_DAYS,
  'SYNTHETIC_ERP' AS DATA_ORIGIN,
  'Deterministic scenario anchored to WORK_ORDER_PART consumption' AS SOURCE_ANCHOR,
  'AS-PIADE-ERP-2026-09-25' AS ASSUMPTION_SET_ID
FROM calc;

/* Exactly one synthetic ERP production order per observed machine/day OEE row. */
CREATE OR REPLACE TABLE GOLD.PRODUCTION_ORDER AS
WITH cfg AS (
  SELECT
    MAX(IFF(NAME='ERP_MARGIN_PER_PACKAGE',VALUE,NULL)) AS MARGIN
  FROM GOLD.IT_ASSUMPTION
  WHERE ASSUMPTION_SET_ID='AS-PIADE-ERP-2026-09-25'
)
SELECT
  'PO-B-' || MACHINE_CODE || '-' || TO_CHAR(OEE_DATE,'YYYYMMDD') AS PRODUCTION_ORDER_ID,
  MACHINE_KEY, MACHINE_CODE, OEE_DATE AS PRODUCTION_DATE,
  r.IDEAL_RATE_PPH,
  ROUND(PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH,0) AS PLANNED_CAPACITY_UNITS,
  ROUND(PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH,0) AS TARGET_OUTPUT_UNITS,
  ROUND(PACKAGES_OUT,0) AS ACTUAL_OUTPUT_UNITS,
  ROUND(GREATEST(PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH-PACKAGES_OUT,0),0) AS OUTPUT_SHORTFALL_UNITS,
  c.MARGIN AS CONTRIBUTION_MARGIN_EUR_PER_UNIT,
  ROUND(PACKAGES_OUT*c.MARGIN,2) AS ACTUAL_MARGIN_EUR,
  ROUND(GREATEST(PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH-PACKAGES_OUT,0)*c.MARGIN,2)
    AS MARGIN_EXPOSURE_EUR,
  CASE
    WHEN PACKAGES_OUT >= PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH THEN 'TARGET_MET'
    WHEN PACKAGES_OUT >= PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH*0.90 THEN 'BELOW_TARGET'
    ELSE 'AT_RISK'
  END AS ORDER_STATUS,
  OEE AS ANCHORED_OEE,
  'SYNTHETIC_ERP' AS DATA_ORIGIN,
  'GOLD.PIADE_OEE_DAILY machine/date row' AS SOURCE_ANCHOR,
  'AS-PIADE-ERP-2026-09-25' AS ASSUMPTION_SET_ID
FROM GOLD.PIADE_OEE_DAILY o
JOIN GOLD.OEE_IDEAL_RATE r USING (MACHINE_KEY)
CROSS JOIN cfg c
WHERE o.PLANT_CODE='PLANT_B';

/* Every observed downtime/idle event attaches to its same-machine/day order.
   WORK_ORDER_ID is populated only for fault events that met the WO threshold. */
CREATE OR REPLACE TABLE GOLD.EVENT_PRODUCTION_ORDER_LINK AS
SELECT
  'EV-B-' || e.MACHINE_CODE || '-'
    || TO_CHAR(e.STOP_START,'YYYYMMDDHH24MISSFF6') || '-' || UPPER(e.STOP_STATE)
    AS SOURCE_EVENT_ID,
  p.PRODUCTION_ORDER_ID,
  w.WORK_ORDER_ID,
  e.MACHINE_KEY,e.MACHINE_CODE,e.STOP_START,e.STOP_END,e.STOP_STATE,e.ALARM_CODE,
  e.STOP_DURATION_MIN AS OBSERVED_LOSS_MINUTES,
  ROUND(e.STOP_DURATION_MIN/60.0*r.IDEAL_RATE_PPH,0) AS DERIVED_FORGONE_UNITS,
  e.DATA_ORIGIN AS EVENT_DATA_ORIGIN,
  'SYNTHETIC_ERP' AS DATA_ORIGIN,
  'Observed PIADE stop joined to derived PIADE machine/day' AS SOURCE_ANCHOR
FROM GOLD.PIADE_DOWNTIME_EVENT e
JOIN GOLD.PRODUCTION_ORDER p
  ON p.MACHINE_KEY=e.MACHINE_KEY AND p.PRODUCTION_DATE=TO_DATE(e.STOP_START)
JOIN GOLD.OEE_IDEAL_RATE r ON r.MACHINE_KEY=e.MACHINE_KEY
LEFT JOIN GOLD.WORK_ORDER w
  ON w.PLANT_CODE='PLANT_B' AND w.MACHINE_KEY=e.MACHINE_KEY
 AND w.SOURCE_EVENT_START=e.STOP_START AND w.SOURCE_EVENT_END=e.STOP_END;

CREATE OR REPLACE VIEW GOLD.V_DIGITAL_THREAD AS
SELECT
  e.SOURCE_EVENT_ID,e.STOP_START,e.STOP_END,e.STOP_STATE,e.ALARM_CODE,
  e.OBSERVED_LOSS_MINUTES,e.DERIVED_FORGONE_UNITS,
  p.PRODUCTION_ORDER_ID,p.PRODUCTION_DATE,p.MACHINE_KEY,p.MACHINE_CODE,
  p.TARGET_OUTPUT_UNITS,p.ACTUAL_OUTPUT_UNITS,p.MARGIN_EXPOSURE_EUR,p.ORDER_STATUS,
  e.WORK_ORDER_ID,w.PRIORITY,w.STATUS AS WORK_ORDER_STATUS,
  w.LABOUR_COST,w.PARTS_COST,w.TOTAL_COST,
  wp.WORK_ORDER_PART_ID,wp.MATERIAL_ID,wp.QUANTITY,wp.EXTENDED_COST_EUR,
  m.MATERIAL_NAME,m.MATERIAL_LIMITATION,
  i.ON_HAND_QTY,i.REORDER_POINT,i.LEAD_TIME_DAYS,i.STOCK_STATE,
  e.EVENT_DATA_ORIGIN,e.DATA_ORIGIN AS LINK_ORIGIN,
  p.DATA_ORIGIN AS PRODUCTION_ORDER_ORIGIN,
  w.DATA_ORIGIN AS WORK_ORDER_ORIGIN,
  wp.DATA_ORIGIN AS PART_ORIGIN,i.DATA_ORIGIN AS INVENTORY_ORIGIN,
  e.SOURCE_ANCHOR
FROM GOLD.EVENT_PRODUCTION_ORDER_LINK e
JOIN GOLD.PRODUCTION_ORDER p USING (PRODUCTION_ORDER_ID)
LEFT JOIN GOLD.WORK_ORDER w USING (WORK_ORDER_ID)
LEFT JOIN GOLD.WORK_ORDER_PART wp USING (WORK_ORDER_ID)
LEFT JOIN GOLD.DIM_MATERIAL m USING (MATERIAL_ID)
LEFT JOIN GOLD.INVENTORY_SNAPSHOT i USING (MATERIAL_ID);

/* Five rows: one per PIADE line. All OEE ratios are weighted from raw totals. */
CREATE OR REPLACE VIEW GOLD.V_EXECUTIVE_FLEET AS
WITH oee AS (
  SELECT MACHINE_KEY,MACHINE_CODE,
    SUM(RUN_SEC)/NULLIF(SUM(PLANNED_SEC),0) AS AVAILABILITY,
    SUM(PACKAGES_OUT)/NULLIF(SUM(THEORETICAL_PACKAGES),0) AS PERFORMANCE,
    SUM(PACKAGES_OUT)/NULLIF(SUM(PACKAGES_IN),0) AS QUALITY,
    (SUM(RUN_SEC)/NULLIF(SUM(PLANNED_SEC),0))
      *(SUM(PACKAGES_OUT)/NULLIF(SUM(THEORETICAL_PACKAGES),0))
      *(SUM(PACKAGES_OUT)/NULLIF(SUM(PACKAGES_IN),0)) AS OEE,
    SUM(DOWNTIME_SEC)/3600 AS BREAKDOWN_HOURS,SUM(IDLE_SEC)/3600 AS IDLE_HOURS,
    SUM(PACKAGES_OUT) AS ACTUAL_OUTPUT_UNITS
  FROM GOLD.PIADE_OEE_DAILY GROUP BY MACHINE_KEY,MACHINE_CODE
), risk AS (
  SELECT r.*,TO_TIMESTAMP_NTZ(r.HOUR_TS/1000000000) HOUR_TIMESTAMP,
    ROW_NUMBER() OVER(PARTITION BY MACHINE_KEY ORDER BY HOUR_TS DESC) rn
  FROM ML.PLANT_B_RISK_SCORE r
), trust AS (
  SELECT SCOPE,AUC,AVG_PRECISION,TOP_DECILE_PRECISION,
         BASELINE_TOP_DECILE_PRECISION,
         IFF(TOP_DECILE_PRECISION>BASELINE_TOP_DECILE_PRECISION,
             'MODEL_OUTPERFORMS_PERSISTENCE','MODEL_DOES_NOT_OUTPERFORM_PERSISTENCE') AS MODEL_VS_BASELINE_TRUST
  FROM ML.PLANT_B_MODEL_METRICS WHERE SCOPE<>'FLEET'
), po AS (
  SELECT MACHINE_KEY,SUM(MARGIN_EXPOSURE_EUR) MARGIN_EXPOSURE_EUR
  FROM GOLD.PRODUCTION_ORDER GROUP BY MACHINE_KEY
), wo AS (
  SELECT MACHINE_KEY,COUNT(*) WORK_ORDER_COUNT FROM GOLD.WORK_ORDER
  WHERE PLANT_CODE='PLANT_B' GROUP BY MACHINE_KEY
)
SELECT o.MACHINE_KEY,o.MACHINE_CODE,o.AVAILABILITY,o.PERFORMANCE,o.QUALITY,o.OEE,
  r.HOUR_TIMESTAMP AS LAST_SCORED_HOUR,r.RISK_SCORE AS LAST_RISK_SCORE,
  r.RISK_PERCENTILE,r.RISK_BAND,t.AUC,t.AVG_PRECISION,
  t.TOP_DECILE_PRECISION,t.BASELINE_TOP_DECILE_PRECISION,t.MODEL_VS_BASELINE_TRUST,
  o.BREAKDOWN_HOURS,o.IDLE_HOURS,o.ACTUAL_OUTPUT_UNITS,
  p.MARGIN_EXPOSURE_EUR,COALESCE(w.WORK_ORDER_COUNT,0) WORK_ORDER_COUNT,
  /* Inventory is a site-level material position. Attributing one shared kit
     to every line that ever consumed it double-counts the same risk. */
  CAST(NULL AS NUMBER) STOCK_RISK_COUNT,
  'DERIVED_FROM_OBSERVED + SYNTHETIC_ERP' AS DATA_ORIGIN
FROM oee o LEFT JOIN risk r ON r.MACHINE_KEY=o.MACHINE_KEY AND r.rn=1
LEFT JOIN trust t ON t.SCOPE=o.MACHINE_CODE LEFT JOIN po p USING(MACHINE_KEY)
LEFT JOIN wo w USING(MACHINE_KEY);

/* PIADE-only financial contract. Waiting exposure belongs to planning;
   breakdown repair and fault-linked production exposure belong to maintenance. */
CREATE OR REPLACE VIEW GOLD.V_PIADE_COST_BY_MACHINE AS
WITH maintenance AS (
  SELECT MACHINE_CODE,
    COUNT(*) WORK_ORDERS,
    SUM(SOURCE_EVENT_MINUTES)/60 BREAKDOWN_HOURS,
    SUM(LABOUR_COST) LABOUR_COST,
    SUM(PARTS_COST) PARTS_COST,
    SUM(LOST_PRODUCTION_COST) BREAKDOWN_FORGONE_MARGIN,
    SUM(TOTAL_COST) MAINTENANCE_COST,
    AVG(TOTAL_COST) AVG_COST_PER_ORDER
  FROM GOLD.WORK_ORDER
  WHERE PLANT_CODE='PLANT_B'
  GROUP BY MACHINE_CODE
), waiting AS (
  SELECT MACHINE_CODE,
    COUNT(*) IDLE_INCIDENTS,
    SUM(LOSS_MINUTES)/60 IDLE_HOURS,
    SUM(FORGONE_MARGIN) IDLE_FORGONE_MARGIN
  FROM GOLD.PRODUCTION_LOSS_INCIDENT
  WHERE PLANT_CODE='PLANT_B'
  GROUP BY MACHINE_CODE
)
SELECT 'PLANT_B' PLANT_CODE,m.MACHINE_CODE,m.WORK_ORDERS,m.BREAKDOWN_HOURS,
  m.LABOUR_COST,m.PARTS_COST,m.BREAKDOWN_FORGONE_MARGIN,m.MAINTENANCE_COST,
  m.AVG_COST_PER_ORDER,COALESCE(w.IDLE_INCIDENTS,0) IDLE_INCIDENTS,
  COALESCE(w.IDLE_HOURS,0) IDLE_HOURS,
  COALESCE(w.IDLE_FORGONE_MARGIN,0) IDLE_FORGONE_MARGIN,
  100*DIV0(COALESCE(w.IDLE_FORGONE_MARGIN,0),
    m.MAINTENANCE_COST+COALESCE(w.IDLE_FORGONE_MARGIN,0)) PCT_COST_FROM_IDLING,
  'SYNTHETIC_IT' DATA_ORIGIN
FROM maintenance m LEFT JOIN waiting w USING(MACHINE_CODE);

CREATE OR REPLACE VIEW GOLD.V_EXECUTIVE_KPI AS
SELECT
  'PLANT_B' AS SITE_CODE,
  MAX(d.OEE_DATE) AS DATA_AS_OF,
  IFF(m.TOP_DECILE_PRECISION>m.BASELINE_TOP_DECILE_PRECISION,
      'BLIND_TEST_MODEL_OUTPERFORMS_PERSISTENCE',
      'BLIND_TEST_MODEL_DOES_NOT_OUTPERFORM_PERSISTENCE') AS MODEL_STATUS,
  SUM(d.RUN_SEC)/NULLIF(SUM(d.PLANNED_SEC),0) AS AVAILABILITY,
  SUM(d.PACKAGES_OUT)/NULLIF(SUM(d.THEORETICAL_PACKAGES),0) AS PERFORMANCE,
  SUM(d.PACKAGES_OUT)/NULLIF(SUM(d.PACKAGES_IN),0) AS QUALITY,
  (SUM(d.RUN_SEC)/NULLIF(SUM(d.PLANNED_SEC),0))
   *(SUM(d.PACKAGES_OUT)/NULLIF(SUM(d.THEORETICAL_PACKAGES),0))
   *(SUM(d.PACKAGES_OUT)/NULLIF(SUM(d.PACKAGES_IN),0)) AS SITE_WEIGHTED_OEE,
  SUM(d.PACKAGES_OUT) AS ACTUAL_OUTPUT_UNITS,
  SUM(d.DOWNTIME_SEC)/3600 AS BREAKDOWN_HOURS,SUM(d.IDLE_SEC)/3600 AS IDLE_HOURS,
  (SELECT SUM(MARGIN_EXPOSURE_EUR) FROM GOLD.PRODUCTION_ORDER) AS ESTIMATED_MARGIN_EXPOSURE_EUR,
  (SELECT COUNT(*) FROM GOLD.WORK_ORDER WHERE PLANT_CODE='PLANT_B') AS WORK_ORDER_COUNT,
  (SELECT COUNT(*) FROM GOLD.INVENTORY_SNAPSHOT WHERE STOCK_STATE IN ('STOCKOUT','REORDER')) AS STOCK_RISK_COUNT,
  m.AUC AS MODEL_AUC,m.AVG_PRECISION AS MODEL_AVG_PRECISION,
  m.TOP_DECILE_PRECISION,m.TOP_DECILE_RECALL,
  m.BASELINE_AUC,m.BASELINE_AVG_PRECISION,m.BASELINE_TOP_DECILE_PRECISION,
  'DERIVED_FROM_OBSERVED + SYNTHETIC_ERP' AS DATA_ORIGIN
FROM GOLD.PIADE_OEE_DAILY d
CROSS JOIN ML.PLANT_B_MODEL_METRICS m
WHERE m.SCOPE='FLEET'
GROUP BY m.AUC,m.AVG_PRECISION,m.TOP_DECILE_PRECISION,m.TOP_DECILE_RECALL,
         m.BASELINE_AUC,m.BASELINE_AVG_PRECISION,m.BASELINE_TOP_DECILE_PRECISION;

/* Cross-functional queue: one best-evidence action per line and function.
   Ranking is deterministic and source keys permit drill-through. */
CREATE OR REPLACE VIEW GOLD.V_EXECUTIVE_ACTION_QUEUE AS
WITH actions AS (
  SELECT 'MAINTENANCE|'||MACHINE_CODE ACTION_KEY,'MAINTENANCE' OWNER_FUNCTION,
    MACHINE_CODE, CASE RISK_BAND WHEN 'HIGH' THEN 'P1' WHEN 'ELEVATED' THEN 'P2' ELSE 'P3' END PRIORITY,
    RISK_BAND RISK_STATE,
    'Latest blind-test risk='||ROUND(LAST_RISK_SCORE,3)||'; breakdown hours='||ROUND(BREAKDOWN_HOURS,1) EVIDENCE,
    'Review recent alarm pattern and schedule inspection only if operational evidence agrees.' RECOMMENDED_ACTION,
    MARGIN_EXPOSURE_EUR PRODUCTION_EXPOSURE_EUR,
    MACHINE_KEY SOURCE_KEYS,'ML.PLANT_B_RISK_SCORE; GOLD.PIADE_OEE_DAILY' PROVENANCE
  FROM GOLD.V_EXECUTIVE_FLEET
  UNION ALL
  SELECT 'PLANNING|'||MACHINE_CODE,'PLANNING',MACHINE_CODE,
    IFF(IDLE_HOURS>BREAKDOWN_HOURS,'P1','P3'),
    IFF(IDLE_HOURS>BREAKDOWN_HOURS,'IDLE_DOMINANT','BREAKDOWN_DOMINANT'),
    'Idle hours='||ROUND(IDLE_HOURS,1)||'; breakdown hours='||ROUND(BREAKDOWN_HOURS,1),
    'Validate schedule, upstream supply and changeover constraints before assigning maintenance.',
    MARGIN_EXPOSURE_EUR,MACHINE_KEY,'GOLD.PIADE_OEE_DAILY; GOLD.PRODUCTION_ORDER'
  FROM GOLD.V_EXECUTIVE_FLEET
  UNION ALL
  SELECT 'SUPPLY|'||p.MACHINE_CODE||'|'||i.MATERIAL_ID,'SUPPLY_CHAIN',p.MACHINE_CODE,
    IFF(i.STOCK_STATE='STOCKOUT','P1','P2'),i.STOCK_STATE,
    'Material='||i.MATERIAL_ID||'; on hand='||i.ON_HAND_QTY||'; reorder='||i.REORDER_POINT,
    'Review the generic service-kit scenario; do not infer a physical component from the anonymised cause.',
    p.MARGIN_EXPOSURE_EUR,p.PRODUCTION_ORDER_ID||';'||i.MATERIAL_ID,
    'GOLD.INVENTORY_SNAPSHOT; GOLD.WORK_ORDER_PART; GOLD.PRODUCTION_ORDER'
  FROM GOLD.INVENTORY_SNAPSHOT i
  JOIN GOLD.WORK_ORDER_PART wp USING(MATERIAL_ID)
  JOIN GOLD.PRODUCTION_ORDER p
    ON p.MACHINE_KEY=wp.MACHINE_KEY AND p.PRODUCTION_DATE=TO_DATE(wp.SOURCE_EVENT_START)
  WHERE i.STOCK_STATE IN ('STOCKOUT','REORDER')
)
SELECT ROW_NUMBER() OVER(ORDER BY
  CASE PRIORITY WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,
  PRODUCTION_EXPOSURE_EUR DESC,ACTION_KEY) AS ACTION_RANK,
  *,'DERIVED_FROM_OBSERVED + SYNTHETIC_ERP' AS DATA_ORIGIN
FROM actions
QUALIFY ROW_NUMBER() OVER(PARTITION BY OWNER_FUNCTION,MACHINE_CODE ORDER BY
  CASE PRIORITY WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,
  PRODUCTION_EXPOSURE_EUR DESC,ACTION_KEY)=1;

/* Six bounded rows maximum: fleet plus five lines, suitable for Q&A context. */
CREATE OR REPLACE VIEW GOLD.V_ANALYST_CONTEXT AS
SELECT 'LINE' GRAIN,MACHINE_CODE,
  OEE,AVAILABILITY,PERFORMANCE,QUALITY,BREAKDOWN_HOURS,IDLE_HOURS,
  ACTUAL_OUTPUT_UNITS,MARGIN_EXPOSURE_EUR,WORK_ORDER_COUNT,STOCK_RISK_COUNT,
  LAST_RISK_SCORE,RISK_BAND,MODEL_VS_BASELINE_TRUST,DATA_ORIGIN
FROM GOLD.V_EXECUTIVE_FLEET
UNION ALL
SELECT 'FLEET','ALL',
  SITE_WEIGHTED_OEE,AVAILABILITY,PERFORMANCE,QUALITY,BREAKDOWN_HOURS,IDLE_HOURS,
  ACTUAL_OUTPUT_UNITS,ESTIMATED_MARGIN_EXPOSURE_EUR,WORK_ORDER_COUNT,STOCK_RISK_COUNT,
  NULL,NULL,IFF(TOP_DECILE_PRECISION>BASELINE_TOP_DECILE_PRECISION,
                'MODEL_OUTPERFORMS_PERSISTENCE','MODEL_DOES_NOT_OUTPERFORM_PERSISTENCE'),
  DATA_ORIGIN
FROM GOLD.V_EXECUTIVE_KPI;

/* ==========================================================================
   Reconciliation, lineage, orphan and determinism checks.
   A non-zero orphan/mismatch count is a deployment failure.
   ========================================================================== */
SELECT 'PRODUCTION_ORDER_ONE_PER_MACHINE_DAY' CHECK_NAME,
  (SELECT COUNT(*) FROM GOLD.PIADE_OEE_DAILY WHERE PLANT_CODE='PLANT_B') EXPECTED,
  (SELECT COUNT(*) FROM GOLD.PRODUCTION_ORDER) ACTUAL;

SELECT 'PART_ROWS_MATCH_CONSUMING_WORK_ORDERS' CHECK_NAME,
  (SELECT COUNT(*) FROM GOLD.WORK_ORDER WHERE PLANT_CODE='PLANT_B' AND PARTS_COST>0) EXPECTED,
  (SELECT COUNT(*) FROM GOLD.WORK_ORDER_PART) ACTUAL
UNION ALL
SELECT 'EVENT_LINKS_MATCH_ANCHORED_EVENTS',
  (SELECT COUNT(*) FROM GOLD.PIADE_DOWNTIME_EVENT e
   WHERE EXISTS (SELECT 1 FROM GOLD.PIADE_OEE_DAILY d
                 WHERE d.MACHINE_KEY=e.MACHINE_KEY AND d.OEE_DATE=TO_DATE(e.STOP_START))),
  (SELECT COUNT(*) FROM GOLD.EVENT_PRODUCTION_ORDER_LINK);

SELECT
  COUNT_IF(p.PRODUCTION_ORDER_ID IS NULL) AS ORPHAN_PRODUCTION_ORDERS,
  COUNT_IF(wp.WORK_ORDER_ID IS NOT NULL AND w.WORK_ORDER_ID IS NULL) AS ORPHAN_PART_WORK_ORDERS,
  COUNT_IF(wp.MATERIAL_ID IS NOT NULL AND m.MATERIAL_ID IS NULL) AS ORPHAN_MATERIALS,
  COUNT_IF(i.MATERIAL_ID IS NULL) AS MATERIALS_WITHOUT_INVENTORY
FROM GOLD.DIM_MATERIAL m
LEFT JOIN GOLD.WORK_ORDER_PART wp USING(MATERIAL_ID)
LEFT JOIN GOLD.WORK_ORDER w USING(WORK_ORDER_ID)
LEFT JOIN GOLD.INVENTORY_SNAPSHOT i USING(MATERIAL_ID)
LEFT JOIN GOLD.PRODUCTION_ORDER p
  ON p.MACHINE_KEY=wp.MACHINE_KEY AND p.PRODUCTION_DATE=TO_DATE(wp.SOURCE_EVENT_START);

SELECT COUNT(*) PART_ROWS,
  ROUND(SUM(w.PARTS_COST),2) WORK_ORDER_PARTS_EUR,
  ROUND(SUM(wp.EXTENDED_COST_EUR),2) LINKED_PARTS_EUR,
  ROUND(SUM(w.PARTS_COST-wp.EXTENDED_COST_EUR),6) RECONCILIATION_DIFFERENCE_EUR,
  COUNT_IF(ABS(w.PARTS_COST-wp.EXTENDED_COST_EUR)>0.000001) MISMATCH_ROWS
FROM GOLD.WORK_ORDER_PART wp JOIN GOLD.WORK_ORDER w USING(WORK_ORDER_ID);

SELECT COUNT_IF(DATA_ORIGIN<>'SYNTHETIC_ERP') WRONG_MATERIAL_ORIGIN FROM GOLD.DIM_MATERIAL;
SELECT COUNT_IF(DATA_ORIGIN<>'SYNTHETIC_ERP') WRONG_PART_ORIGIN FROM GOLD.WORK_ORDER_PART;
SELECT COUNT_IF(DATA_ORIGIN<>'SYNTHETIC_ERP') WRONG_INVENTORY_ORIGIN FROM GOLD.INVENTORY_SNAPSHOT;
SELECT COUNT_IF(DATA_ORIGIN<>'SYNTHETIC_ERP') WRONG_ORDER_ORIGIN FROM GOLD.PRODUCTION_ORDER;

/* Recompute hash-driven values: all mismatch counts must be zero. */
SELECT COUNT_IF(QUANTITY <> 1+(ABS(HASH(WORK_ORDER_ID||'|quantity'))%3)) QUANTITY_MISMATCHES
FROM GOLD.WORK_ORDER_PART;
SELECT COUNT_IF(LEAD_TIME_DAYS <> 2+(ABS(HASH(MATERIAL_ID||'|lead'))%13)) LEAD_TIME_MISMATCHES
FROM GOLD.INVENTORY_SNAPSHOT;

SELECT COUNT_IF(MACHINE_KEY NOT LIKE 'PLANT_B:%') NON_PIADE_MACHINE_ROWS FROM GOLD.PRODUCTION_ORDER;
SELECT COUNT_IF(SOURCE_ANCHOR IS NULL OR DATA_ORIGIN<>'SYNTHETIC_ERP') UNTRACEABLE_ROWS
FROM GOLD.PRODUCTION_ORDER;
SELECT COUNT(*) EXECUTIVE_FLEET_ROWS,COUNT(DISTINCT MACHINE_CODE) EXECUTIVE_LINES
FROM GOLD.V_EXECUTIVE_FLEET;
SELECT COUNT(*)-COUNT(DISTINCT SOURCE_EVENT_ID) DUPLICATE_SOURCE_EVENT_IDS
FROM GOLD.EVENT_PRODUCTION_ORDER_LINK;
SELECT COUNT(*) PIADE_COST_ROWS,COUNT(DISTINCT MACHINE_CODE) PIADE_COST_LINES
FROM GOLD.V_PIADE_COST_BY_MACHINE;

SELECT COUNT_IF(
  p.PLANNED_CAPACITY_UNITS <> ROUND(d.PLANNED_SEC/3600.0*r.IDEAL_RATE_PPH,0)
  OR p.TARGET_OUTPUT_UNITS <> p.PLANNED_CAPACITY_UNITS
) AS CAPACITY_CONTRACT_MISMATCHES
FROM GOLD.PRODUCTION_ORDER p
JOIN GOLD.PIADE_OEE_DAILY d
  ON d.MACHINE_KEY=p.MACHINE_KEY AND d.OEE_DATE=p.PRODUCTION_DATE
JOIN GOLD.OEE_IDEAL_RATE r ON r.MACHINE_KEY=p.MACHINE_KEY;

SELECT COUNT(*) AS RETIRED_TARGET_UPLIFT_ROWS
FROM GOLD.IT_ASSUMPTION
WHERE ASSUMPTION_SET_ID='AS-PIADE-ERP-2026-09-25'
  AND NAME='ERP_TARGET_UPLIFT';

SELECT DATA_AS_OF,MODEL_STATUS,SITE_WEIGHTED_OEE,ESTIMATED_MARGIN_EXPOSURE_EUR
FROM GOLD.V_EXECUTIVE_KPI;
